import PartialProps from '../types'
export function DeviconThreedsmax(p: PartialProps): React.JSX.Element
export function DeviconAarch64(p: PartialProps): React.JSX.Element
export function DeviconAdonisjs(p: PartialProps): React.JSX.Element
export function DeviconAftereffects(p: PartialProps): React.JSX.Element
export function DeviconAkka(p: PartialProps): React.JSX.Element
export function DeviconAlgolia(p: PartialProps): React.JSX.Element
export function DeviconAlpinejs(p: PartialProps): React.JSX.Element
export function DeviconAmazonwebservices(p: PartialProps): React.JSX.Element
export function DeviconAnaconda(p: PartialProps): React.JSX.Element
export function DeviconAndroid(p: PartialProps): React.JSX.Element
export function DeviconAndroidstudio(p: PartialProps): React.JSX.Element
export function DeviconAngular(p: PartialProps): React.JSX.Element
export function DeviconAngularjs(p: PartialProps): React.JSX.Element
export function DeviconAngularmaterial(p: PartialProps): React.JSX.Element
export function DeviconAnsible(p: PartialProps): React.JSX.Element
export function DeviconAntdesign(p: PartialProps): React.JSX.Element
export function DeviconApache(p: PartialProps): React.JSX.Element
export function DeviconApacheairflow(p: PartialProps): React.JSX.Element
export function DeviconApachekafka(p: PartialProps): React.JSX.Element
export function DeviconApachespark(p: PartialProps): React.JSX.Element
export function DeviconApl(p: PartialProps): React.JSX.Element
export function DeviconAppcelerator(p: PartialProps): React.JSX.Element
export function DeviconApple(p: PartialProps): React.JSX.Element
export function DeviconAppwrite(p: PartialProps): React.JSX.Element
export function DeviconArchlinux(p: PartialProps): React.JSX.Element
export function DeviconArduino(p: PartialProps): React.JSX.Element
export function DeviconArgocd(p: PartialProps): React.JSX.Element
export function DeviconAstro(p: PartialProps): React.JSX.Element
export function DeviconAtom(p: PartialProps): React.JSX.Element
export function DeviconAwk(p: PartialProps): React.JSX.Element
export function DeviconAxios(p: PartialProps): React.JSX.Element
export function DeviconAzure(p: PartialProps): React.JSX.Element
export function DeviconAzuredevops(p: PartialProps): React.JSX.Element
export function DeviconAzuresqldatabase(p: PartialProps): React.JSX.Element
export function DeviconBabel(p: PartialProps): React.JSX.Element
export function DeviconBackbonejs(p: PartialProps): React.JSX.Element
export function DeviconBallerina(p: PartialProps): React.JSX.Element
export function DeviconBamboo(p: PartialProps): React.JSX.Element
export function DeviconBash(p: PartialProps): React.JSX.Element
export function DeviconBeats(p: PartialProps): React.JSX.Element
export function DeviconBehance(p: PartialProps): React.JSX.Element
export function DeviconBitbucket(p: PartialProps): React.JSX.Element
export function DeviconBlazor(p: PartialProps): React.JSX.Element
export function DeviconBlender(p: PartialProps): React.JSX.Element
export function DeviconBootstrap(p: PartialProps): React.JSX.Element
export function DeviconBower(p: PartialProps): React.JSX.Element
export function DeviconBrowserstack(p: PartialProps): React.JSX.Element
export function DeviconBulma(p: PartialProps): React.JSX.Element
export function DeviconBun(p: PartialProps): React.JSX.Element
export function DeviconC(p: PartialProps): React.JSX.Element
export function DeviconCairo(p: PartialProps): React.JSX.Element
export function DeviconCakephp(p: PartialProps): React.JSX.Element
export function DeviconCanva(p: PartialProps): React.JSX.Element
export function DeviconCapacitor(p: PartialProps): React.JSX.Element
export function DeviconCarbon(p: PartialProps): React.JSX.Element
export function DeviconCassandra(p: PartialProps): React.JSX.Element
export function DeviconCentos(p: PartialProps): React.JSX.Element
export function DeviconCeylon(p: PartialProps): React.JSX.Element
export function DeviconChrome(p: PartialProps): React.JSX.Element
export function DeviconCircleci(p: PartialProps): React.JSX.Element
export function DeviconClarity(p: PartialProps): React.JSX.Element
export function DeviconClion(p: PartialProps): React.JSX.Element
export function DeviconClojure(p: PartialProps): React.JSX.Element
export function DeviconClojurescript(p: PartialProps): React.JSX.Element
export function DeviconCloudflare(p: PartialProps): React.JSX.Element
export function DeviconCloudflareworkers(p: PartialProps): React.JSX.Element
export function DeviconCmake(p: PartialProps): React.JSX.Element
export function DeviconCodeac(p: PartialProps): React.JSX.Element
export function DeviconCodecov(p: PartialProps): React.JSX.Element
export function DeviconCodeigniter(p: PartialProps): React.JSX.Element
export function DeviconCodepen(p: PartialProps): React.JSX.Element
export function DeviconCoffeescript(p: PartialProps): React.JSX.Element
export function DeviconComposer(p: PartialProps): React.JSX.Element
export function DeviconConfluence(p: PartialProps): React.JSX.Element
export function DeviconConsul(p: PartialProps): React.JSX.Element
export function DeviconContao(p: PartialProps): React.JSX.Element
export function DeviconCorejs(p: PartialProps): React.JSX.Element
export function DeviconCosmosdb(p: PartialProps): React.JSX.Element
export function DeviconCouchbase(p: PartialProps): React.JSX.Element
export function DeviconCouchdb(p: PartialProps): React.JSX.Element
export function DeviconCplusplus(p: PartialProps): React.JSX.Element
export function DeviconCrystal(p: PartialProps): React.JSX.Element
export function DeviconCsharp(p: PartialProps): React.JSX.Element
export function DeviconCss3(p: PartialProps): React.JSX.Element
export function DeviconCucumber(p: PartialProps): React.JSX.Element
export function DeviconCypressio(p: PartialProps): React.JSX.Element
export function DeviconD3js(p: PartialProps): React.JSX.Element
export function DeviconDart(p: PartialProps): React.JSX.Element
export function DeviconDatagrip(p: PartialProps): React.JSX.Element
export function DeviconDataspell(p: PartialProps): React.JSX.Element
export function DeviconDbeaver(p: PartialProps): React.JSX.Element
export function DeviconDebian(p: PartialProps): React.JSX.Element
export function DeviconDenojs(p: PartialProps): React.JSX.Element
export function DeviconDevicon(p: PartialProps): React.JSX.Element
export function DeviconDigitalocean(p: PartialProps): React.JSX.Element
export function DeviconDiscordjs(p: PartialProps): React.JSX.Element
export function DeviconDjango(p: PartialProps): React.JSX.Element
export function DeviconDjangorest(p: PartialProps): React.JSX.Element
export function DeviconDocker(p: PartialProps): React.JSX.Element
export function DeviconDoctrine(p: PartialProps): React.JSX.Element
export function DeviconDotnet(p: PartialProps): React.JSX.Element
export function DeviconDotnetcore(p: PartialProps): React.JSX.Element
export function DeviconDreamweaver(p: PartialProps): React.JSX.Element
export function DeviconDropwizard(p: PartialProps): React.JSX.Element
export function DeviconDrupal(p: PartialProps): React.JSX.Element
export function DeviconDynamodb(p: PartialProps): React.JSX.Element
export function DeviconEclipse(p: PartialProps): React.JSX.Element
export function DeviconEcto(p: PartialProps): React.JSX.Element
export function DeviconElasticsearch(p: PartialProps): React.JSX.Element
export function DeviconElectron(p: PartialProps): React.JSX.Element
export function DeviconEleventy(p: PartialProps): React.JSX.Element
export function DeviconElixir(p: PartialProps): React.JSX.Element
export function DeviconElm(p: PartialProps): React.JSX.Element
export function DeviconEmacs(p: PartialProps): React.JSX.Element
export function DeviconEmbeddedc(p: PartialProps): React.JSX.Element
export function DeviconEmber(p: PartialProps): React.JSX.Element
export function DeviconEnvoy(p: PartialProps): React.JSX.Element
export function DeviconErlang(p: PartialProps): React.JSX.Element
export function DeviconEslint(p: PartialProps): React.JSX.Element
export function DeviconExpress(p: PartialProps): React.JSX.Element
export function DeviconFacebook(p: PartialProps): React.JSX.Element
export function DeviconFastapi(p: PartialProps): React.JSX.Element
export function DeviconFastify(p: PartialProps): React.JSX.Element
export function DeviconFaunadb(p: PartialProps): React.JSX.Element
export function DeviconFeathersjs(p: PartialProps): React.JSX.Element
export function DeviconFedora(p: PartialProps): React.JSX.Element
export function DeviconFigma(p: PartialProps): React.JSX.Element
export function DeviconFilezilla(p: PartialProps): React.JSX.Element
export function DeviconFirebase(p: PartialProps): React.JSX.Element
export function DeviconFirefox(p: PartialProps): React.JSX.Element
export function DeviconFlask(p: PartialProps): React.JSX.Element
export function DeviconFlutter(p: PartialProps): React.JSX.Element
export function DeviconFortran(p: PartialProps): React.JSX.Element
export function DeviconFoundation(p: PartialProps): React.JSX.Element
export function DeviconFramermotion(p: PartialProps): React.JSX.Element
export function DeviconFramework7(p: PartialProps): React.JSX.Element
export function DeviconFsharp(p: PartialProps): React.JSX.Element
export function DeviconGatling(p: PartialProps): React.JSX.Element
export function DeviconGatsby(p: PartialProps): React.JSX.Element
export function DeviconGazebo(p: PartialProps): React.JSX.Element
export function DeviconGcc(p: PartialProps): React.JSX.Element
export function DeviconGentoo(p: PartialProps): React.JSX.Element
export function DeviconGhost(p: PartialProps): React.JSX.Element
export function DeviconGimp(p: PartialProps): React.JSX.Element
export function DeviconGit(p: PartialProps): React.JSX.Element
export function DeviconGitbook(p: PartialProps): React.JSX.Element
export function DeviconGithub(p: PartialProps): React.JSX.Element
export function DeviconGithubactions(p: PartialProps): React.JSX.Element
export function DeviconGithubcodespaces(p: PartialProps): React.JSX.Element
export function DeviconGitlab(p: PartialProps): React.JSX.Element
export function DeviconGitpod(p: PartialProps): React.JSX.Element
export function DeviconGitter(p: PartialProps): React.JSX.Element
export function DeviconGo(p: PartialProps): React.JSX.Element
export function DeviconGodot(p: PartialProps): React.JSX.Element
export function DeviconGoland(p: PartialProps): React.JSX.Element
export function DeviconGoogle(p: PartialProps): React.JSX.Element
export function DeviconGooglecloud(p: PartialProps): React.JSX.Element
export function DeviconGradle(p: PartialProps): React.JSX.Element
export function DeviconGrafana(p: PartialProps): React.JSX.Element
export function DeviconGrails(p: PartialProps): React.JSX.Element
export function DeviconGraphql(p: PartialProps): React.JSX.Element
export function DeviconGroovy(p: PartialProps): React.JSX.Element
export function DeviconGrpc(p: PartialProps): React.JSX.Element
export function DeviconGrunt(p: PartialProps): React.JSX.Element
export function DeviconGulp(p: PartialProps): React.JSX.Element
export function DeviconHadoop(p: PartialProps): React.JSX.Element
export function DeviconHandlebars(p: PartialProps): React.JSX.Element
export function DeviconHardhat(p: PartialProps): React.JSX.Element
export function DeviconHarvester(p: PartialProps): React.JSX.Element
export function DeviconHaskell(p: PartialProps): React.JSX.Element
export function DeviconHaxe(p: PartialProps): React.JSX.Element
export function DeviconHelm(p: PartialProps): React.JSX.Element
export function DeviconHeroku(p: PartialProps): React.JSX.Element
export function DeviconHibernate(p: PartialProps): React.JSX.Element
export function DeviconHomebrew(p: PartialProps): React.JSX.Element
export function DeviconHtml5(p: PartialProps): React.JSX.Element
export function DeviconHugo(p: PartialProps): React.JSX.Element
export function DeviconIe10(p: PartialProps): React.JSX.Element
export function DeviconIfttt(p: PartialProps): React.JSX.Element
export function DeviconIllustrator(p: PartialProps): React.JSX.Element
export function DeviconInfluxdb(p: PartialProps): React.JSX.Element
export function DeviconInkscape(p: PartialProps): React.JSX.Element
export function DeviconInsomnia(p: PartialProps): React.JSX.Element
export function DeviconIntellij(p: PartialProps): React.JSX.Element
export function DeviconIonic(p: PartialProps): React.JSX.Element
export function DeviconJaegertracing(p: PartialProps): React.JSX.Element
export function DeviconJamstack(p: PartialProps): React.JSX.Element
export function DeviconJasmine(p: PartialProps): React.JSX.Element
export function DeviconJava(p: PartialProps): React.JSX.Element
export function DeviconJavascript(p: PartialProps): React.JSX.Element
export function DeviconJeet(p: PartialProps): React.JSX.Element
export function DeviconJekyll(p: PartialProps): React.JSX.Element
export function DeviconJenkins(p: PartialProps): React.JSX.Element
export function DeviconJest(p: PartialProps): React.JSX.Element
export function DeviconJetbrains(p: PartialProps): React.JSX.Element
export function DeviconJetpackcompose(p: PartialProps): React.JSX.Element
export function DeviconJira(p: PartialProps): React.JSX.Element
export function DeviconJiraalign(p: PartialProps): React.JSX.Element
export function DeviconJquery(p: PartialProps): React.JSX.Element
export function DeviconJson(p: PartialProps): React.JSX.Element
export function DeviconJule(p: PartialProps): React.JSX.Element
export function DeviconJulia(p: PartialProps): React.JSX.Element
export function DeviconJunit(p: PartialProps): React.JSX.Element
export function DeviconJupyter(p: PartialProps): React.JSX.Element
export function DeviconK3os(p: PartialProps): React.JSX.Element
export function DeviconK3s(p: PartialProps): React.JSX.Element
export function DeviconK6(p: PartialProps): React.JSX.Element
export function DeviconKaggle(p: PartialProps): React.JSX.Element
export function DeviconKaratelabs(p: PartialProps): React.JSX.Element
export function DeviconKarma(p: PartialProps): React.JSX.Element
export function DeviconKdeneon(p: PartialProps): React.JSX.Element
export function DeviconKeras(p: PartialProps): React.JSX.Element
export function DeviconKibana(p: PartialProps): React.JSX.Element
export function DeviconKnexjs(p: PartialProps): React.JSX.Element
export function DeviconKnockout(p: PartialProps): React.JSX.Element
export function DeviconKotlin(p: PartialProps): React.JSX.Element
export function DeviconKrakenjs(p: PartialProps): React.JSX.Element
export function DeviconKtor(p: PartialProps): React.JSX.Element
export function DeviconKubernetes(p: PartialProps): React.JSX.Element
export function DeviconLabview(p: PartialProps): React.JSX.Element
export function DeviconLaravel(p: PartialProps): React.JSX.Element
export function DeviconLatex(p: PartialProps): React.JSX.Element
export function DeviconLess(p: PartialProps): React.JSX.Element
export function DeviconLinkedin(p: PartialProps): React.JSX.Element
export function DeviconLinux(p: PartialProps): React.JSX.Element
export function DeviconLiquibase(p: PartialProps): React.JSX.Element
export function DeviconLivewire(p: PartialProps): React.JSX.Element
export function DeviconLlvm(p: PartialProps): React.JSX.Element
export function DeviconLodash(p: PartialProps): React.JSX.Element
export function DeviconLogstash(p: PartialProps): React.JSX.Element
export function DeviconLua(p: PartialProps): React.JSX.Element
export function DeviconLumen(p: PartialProps): React.JSX.Element
export function DeviconMagento(p: PartialProps): React.JSX.Element
export function DeviconMariadb(p: PartialProps): React.JSX.Element
export function DeviconMarkdown(p: PartialProps): React.JSX.Element
export function DeviconMaterializecss(p: PartialProps): React.JSX.Element
export function DeviconMaterialui(p: PartialProps): React.JSX.Element
export function DeviconMatlab(p: PartialProps): React.JSX.Element
export function DeviconMatplotlib(p: PartialProps): React.JSX.Element
export function DeviconMaven(p: PartialProps): React.JSX.Element
export function DeviconMaya(p: PartialProps): React.JSX.Element
export function DeviconMeteor(p: PartialProps): React.JSX.Element
export function DeviconMicrosoftsqlserver(p: PartialProps): React.JSX.Element
export function DeviconMinitab(p: PartialProps): React.JSX.Element
export function DeviconMithril(p: PartialProps): React.JSX.Element
export function DeviconMobx(p: PartialProps): React.JSX.Element
export function DeviconMocha(p: PartialProps): React.JSX.Element
export function DeviconModx(p: PartialProps): React.JSX.Element
export function DeviconMoleculer(p: PartialProps): React.JSX.Element
export function DeviconMongodb(p: PartialProps): React.JSX.Element
export function DeviconMongoose(p: PartialProps): React.JSX.Element
export function DeviconMoodle(p: PartialProps): React.JSX.Element
export function DeviconMsdos(p: PartialProps): React.JSX.Element
export function DeviconMysql(p: PartialProps): React.JSX.Element
export function DeviconNano(p: PartialProps): React.JSX.Element
export function DeviconNeo4j(p: PartialProps): React.JSX.Element
export function DeviconNeovim(p: PartialProps): React.JSX.Element
export function DeviconNestjs(p: PartialProps): React.JSX.Element
export function DeviconNetlify(p: PartialProps): React.JSX.Element
export function DeviconNetworkx(p: PartialProps): React.JSX.Element
export function DeviconNextjs(p: PartialProps): React.JSX.Element
export function DeviconNginx(p: PartialProps): React.JSX.Element
export function DeviconNgrx(p: PartialProps): React.JSX.Element
export function DeviconNhibernate(p: PartialProps): React.JSX.Element
export function DeviconNim(p: PartialProps): React.JSX.Element
export function DeviconNimble(p: PartialProps): React.JSX.Element
export function DeviconNixos(p: PartialProps): React.JSX.Element
export function DeviconNodejs(p: PartialProps): React.JSX.Element
export function DeviconNodemon(p: PartialProps): React.JSX.Element
export function DeviconNodewebkit(p: PartialProps): React.JSX.Element
export function DeviconNomad(p: PartialProps): React.JSX.Element
export function DeviconNorg(p: PartialProps): React.JSX.Element
export function DeviconNotion(p: PartialProps): React.JSX.Element
export function DeviconNpm(p: PartialProps): React.JSX.Element
export function DeviconNuget(p: PartialProps): React.JSX.Element
export function DeviconNumpy(p: PartialProps): React.JSX.Element
export function DeviconNuxtjs(p: PartialProps): React.JSX.Element
export function DeviconOauth(p: PartialProps): React.JSX.Element
export function DeviconObjectivec(p: PartialProps): React.JSX.Element
export function DeviconOcaml(p: PartialProps): React.JSX.Element
export function DeviconOhmyzsh(p: PartialProps): React.JSX.Element
export function DeviconOkta(p: PartialProps): React.JSX.Element
export function DeviconOpenal(p: PartialProps): React.JSX.Element
export function DeviconOpenapi(p: PartialProps): React.JSX.Element
export function DeviconOpencl(p: PartialProps): React.JSX.Element
export function DeviconOpencv(p: PartialProps): React.JSX.Element
export function DeviconOpengl(p: PartialProps): React.JSX.Element
export function DeviconOpenstack(p: PartialProps): React.JSX.Element
export function DeviconOpensuse(p: PartialProps): React.JSX.Element
export function DeviconOpentelemetry(p: PartialProps): React.JSX.Element
export function DeviconOpera(p: PartialProps): React.JSX.Element
export function DeviconOracle(p: PartialProps): React.JSX.Element
export function DeviconOry(p: PartialProps): React.JSX.Element
export function DeviconP5js(p: PartialProps): React.JSX.Element
export function DeviconPacker(p: PartialProps): React.JSX.Element
export function DeviconPandas(p: PartialProps): React.JSX.Element
export function DeviconPerl(p: PartialProps): React.JSX.Element
export function DeviconPfsense(p: PartialProps): React.JSX.Element
export function DeviconPhalcon(p: PartialProps): React.JSX.Element
export function DeviconPhoenix(p: PartialProps): React.JSX.Element
export function DeviconPhotonengine(p: PartialProps): React.JSX.Element
export function DeviconPhotoshop(p: PartialProps): React.JSX.Element
export function DeviconPhp(p: PartialProps): React.JSX.Element
export function DeviconPhpstorm(p: PartialProps): React.JSX.Element
export function DeviconPlaywright(p: PartialProps): React.JSX.Element
export function DeviconPlotly(p: PartialProps): React.JSX.Element
export function DeviconPnpm(p: PartialProps): React.JSX.Element
export function DeviconPodman(p: PartialProps): React.JSX.Element
export function DeviconPoetry(p: PartialProps): React.JSX.Element
export function DeviconPolygon(p: PartialProps): React.JSX.Element
export function DeviconPortainer(p: PartialProps): React.JSX.Element
export function DeviconPostcss(p: PartialProps): React.JSX.Element
export function DeviconPostgresql(p: PartialProps): React.JSX.Element
export function DeviconPostman(p: PartialProps): React.JSX.Element
export function DeviconPowershell(p: PartialProps): React.JSX.Element
export function DeviconPremierepro(p: PartialProps): React.JSX.Element
export function DeviconPrisma(p: PartialProps): React.JSX.Element
export function DeviconProcessing(p: PartialProps): React.JSX.Element
export function DeviconProlog(p: PartialProps): React.JSX.Element
export function DeviconPrometheus(p: PartialProps): React.JSX.Element
export function DeviconProtractor(p: PartialProps): React.JSX.Element
export function DeviconPulsar(p: PartialProps): React.JSX.Element
export function DeviconPulumi(p: PartialProps): React.JSX.Element
export function DeviconPuppeteer(p: PartialProps): React.JSX.Element
export function DeviconPurescript(p: PartialProps): React.JSX.Element
export function DeviconPutty(p: PartialProps): React.JSX.Element
export function DeviconPycharm(p: PartialProps): React.JSX.Element
export function DeviconPypi(p: PartialProps): React.JSX.Element
export function DeviconPyscript(p: PartialProps): React.JSX.Element
export function DeviconPytest(p: PartialProps): React.JSX.Element
export function DeviconPython(p: PartialProps): React.JSX.Element
export function DeviconPytorch(p: PartialProps): React.JSX.Element
export function DeviconQodana(p: PartialProps): React.JSX.Element
export function DeviconQt(p: PartialProps): React.JSX.Element
export function DeviconQuarkus(p: PartialProps): React.JSX.Element
export function DeviconQuasar(p: PartialProps): React.JSX.Element
export function DeviconQwik(p: PartialProps): React.JSX.Element
export function DeviconR(p: PartialProps): React.JSX.Element
export function DeviconRabbitmq(p: PartialProps): React.JSX.Element
export function DeviconRails(p: PartialProps): React.JSX.Element
export function DeviconRailway(p: PartialProps): React.JSX.Element
export function DeviconRancher(p: PartialProps): React.JSX.Element
export function DeviconRaspberrypi(p: PartialProps): React.JSX.Element
export function DeviconReach(p: PartialProps): React.JSX.Element
export function DeviconReact(p: PartialProps): React.JSX.Element
export function DeviconReactbootstrap(p: PartialProps): React.JSX.Element
export function DeviconReactnavigation(p: PartialProps): React.JSX.Element
export function DeviconReadthedocs(p: PartialProps): React.JSX.Element
export function DeviconRealm(p: PartialProps): React.JSX.Element
export function DeviconRect(p: PartialProps): React.JSX.Element
export function DeviconRedhat(p: PartialProps): React.JSX.Element
export function DeviconRedis(p: PartialProps): React.JSX.Element
export function DeviconRedux(p: PartialProps): React.JSX.Element
export function DeviconRenpy(p: PartialProps): React.JSX.Element
export function DeviconReplit(p: PartialProps): React.JSX.Element
export function DeviconRider(p: PartialProps): React.JSX.Element
export function DeviconRocksdb(p: PartialProps): React.JSX.Element
export function DeviconRockylinux(p: PartialProps): React.JSX.Element
export function DeviconRollup(p: PartialProps): React.JSX.Element
export function DeviconRos(p: PartialProps): React.JSX.Element
export function DeviconRspec(p: PartialProps): React.JSX.Element
export function DeviconRstudio(p: PartialProps): React.JSX.Element
export function DeviconRuby(p: PartialProps): React.JSX.Element
export function DeviconRubymine(p: PartialProps): React.JSX.Element
export function DeviconRust(p: PartialProps): React.JSX.Element
export function DeviconRxjs(p: PartialProps): React.JSX.Element
export function DeviconSafari(p: PartialProps): React.JSX.Element
export function DeviconSalesforce(p: PartialProps): React.JSX.Element
export function DeviconSanity(p: PartialProps): React.JSX.Element
export function DeviconSass(p: PartialProps): React.JSX.Element
export function DeviconScala(p: PartialProps): React.JSX.Element
export function DeviconScalingo(p: PartialProps): React.JSX.Element
export function DeviconScikitlearn(p: PartialProps): React.JSX.Element
export function DeviconSdl(p: PartialProps): React.JSX.Element
export function DeviconSelenium(p: PartialProps): React.JSX.Element
export function DeviconSema(p: PartialProps): React.JSX.Element
export function DeviconSentry(p: PartialProps): React.JSX.Element
export function DeviconReactrouter(p: PartialProps): React.JSX.Element
export function DeviconSequelize(p: PartialProps): React.JSX.Element
export function DeviconShopware(p: PartialProps): React.JSX.Element
export function DeviconShotgrid(p: PartialProps): React.JSX.Element
export function DeviconSketch(p: PartialProps): React.JSX.Element
export function DeviconSlack(p: PartialProps): React.JSX.Element
export function DeviconSocketio(p: PartialProps): React.JSX.Element
export function DeviconSolidity(p: PartialProps): React.JSX.Element
export function DeviconSolidjs(p: PartialProps): React.JSX.Element
export function DeviconSonarqube(p: PartialProps): React.JSX.Element
export function DeviconSourcetree(p: PartialProps): React.JSX.Element
export function DeviconSpack(p: PartialProps): React.JSX.Element
export function DeviconSplunk(p: PartialProps): React.JSX.Element
export function DeviconSpring(p: PartialProps): React.JSX.Element
export function DeviconSpss(p: PartialProps): React.JSX.Element
export function DeviconSpyder(p: PartialProps): React.JSX.Element
export function DeviconSqlalchemy(p: PartialProps): React.JSX.Element
export function DeviconSqldeveloper(p: PartialProps): React.JSX.Element
export function DeviconSqlite(p: PartialProps): React.JSX.Element
export function DeviconSsh(p: PartialProps): React.JSX.Element
export function DeviconStackoverflow(p: PartialProps): React.JSX.Element
export function DeviconStata(p: PartialProps): React.JSX.Element
export function DeviconStorybook(p: PartialProps): React.JSX.Element
export function DeviconStreamlit(p: PartialProps): React.JSX.Element
export function DeviconStylus(p: PartialProps): React.JSX.Element
export function DeviconSubversion(p: PartialProps): React.JSX.Element
export function DeviconSupabase(p: PartialProps): React.JSX.Element
export function DeviconSvelte(p: PartialProps): React.JSX.Element
export function DeviconSwagger(p: PartialProps): React.JSX.Element
export function DeviconSwift(p: PartialProps): React.JSX.Element
export function DeviconSwiper(p: PartialProps): React.JSX.Element
export function DeviconSymfony(p: PartialProps): React.JSX.Element
export function DeviconTailwindcss(p: PartialProps): React.JSX.Element
export function DeviconTauri(p: PartialProps): React.JSX.Element
export function DeviconTensorflow(p: PartialProps): React.JSX.Element
export function DeviconTerraform(p: PartialProps): React.JSX.Element
export function DeviconTex(p: PartialProps): React.JSX.Element
export function DeviconThealgorithms(p: PartialProps): React.JSX.Element
export function DeviconThreejs(p: PartialProps): React.JSX.Element
export function DeviconTitaniumsdk(p: PartialProps): React.JSX.Element
export function DeviconTomcat(p: PartialProps): React.JSX.Element
export function DeviconTortoisegit(p: PartialProps): React.JSX.Element
export function DeviconTowergit(p: PartialProps): React.JSX.Element
export function DeviconTraefikmesh(p: PartialProps): React.JSX.Element
export function DeviconTraefikproxy(p: PartialProps): React.JSX.Element
export function DeviconTravis(p: PartialProps): React.JSX.Element
export function DeviconTrello(p: PartialProps): React.JSX.Element
export function DeviconTrpc(p: PartialProps): React.JSX.Element
export function DeviconTwitter(p: PartialProps): React.JSX.Element
export function DeviconTypescript(p: PartialProps): React.JSX.Element
export function DeviconTypo3(p: PartialProps): React.JSX.Element
export function DeviconUbuntu(p: PartialProps): React.JSX.Element
export function DeviconUnifiedmodelinglanguage(p: PartialProps): React.JSX.Element
export function DeviconUnity(p: PartialProps): React.JSX.Element
export function DeviconUnix(p: PartialProps): React.JSX.Element
export function DeviconUnrealengine(p: PartialProps): React.JSX.Element
export function DeviconUwsgi(p: PartialProps): React.JSX.Element
export function DeviconV8(p: PartialProps): React.JSX.Element
export function DeviconVagrant(p: PartialProps): React.JSX.Element
export function DeviconVala(p: PartialProps): React.JSX.Element
export function DeviconVault(p: PartialProps): React.JSX.Element
export function DeviconVercel(p: PartialProps): React.JSX.Element
export function DeviconVertx(p: PartialProps): React.JSX.Element
export function DeviconVim(p: PartialProps): React.JSX.Element
export function DeviconVisualbasic(p: PartialProps): React.JSX.Element
export function DeviconVisualstudio(p: PartialProps): React.JSX.Element
export function DeviconVite(p: PartialProps): React.JSX.Element
export function DeviconVitejs(p: PartialProps): React.JSX.Element
export function DeviconVitess(p: PartialProps): React.JSX.Element
export function DeviconVitest(p: PartialProps): React.JSX.Element
export function DeviconVscode(p: PartialProps): React.JSX.Element
export function DeviconVsphere(p: PartialProps): React.JSX.Element
export function DeviconVuejs(p: PartialProps): React.JSX.Element
export function DeviconVuestorefront(p: PartialProps): React.JSX.Element
export function DeviconVuetify(p: PartialProps): React.JSX.Element
export function DeviconVyper(p: PartialProps): React.JSX.Element
export function DeviconWasm(p: PartialProps): React.JSX.Element
export function DeviconWebflow(p: PartialProps): React.JSX.Element
export function DeviconWeblate(p: PartialProps): React.JSX.Element
export function DeviconWebpack(p: PartialProps): React.JSX.Element
export function DeviconWebstorm(p: PartialProps): React.JSX.Element
export function DeviconWindows11(p: PartialProps): React.JSX.Element
export function DeviconWindows8(p: PartialProps): React.JSX.Element
export function DeviconWoocommerce(p: PartialProps): React.JSX.Element
export function DeviconWordpress(p: PartialProps): React.JSX.Element
export function DeviconXamarin(p: PartialProps): React.JSX.Element
export function DeviconXcode(p: PartialProps): React.JSX.Element
export function DeviconXd(p: PartialProps): React.JSX.Element
export function DeviconXml(p: PartialProps): React.JSX.Element
export function DeviconYaml(p: PartialProps): React.JSX.Element
export function DeviconYarn(p: PartialProps): React.JSX.Element
export function DeviconYii(p: PartialProps): React.JSX.Element
export function DeviconYugabytedb(p: PartialProps): React.JSX.Element
export function DeviconYunohost(p: PartialProps): React.JSX.Element
export function DeviconZend(p: PartialProps): React.JSX.Element
export function DeviconZig(p: PartialProps): React.JSX.Element
