import Devicon from '../devicon'
export const DeviconThreedsmax = p => <Devicon icon='threedsmax' release='2.16.0' {...p}/>
export const DeviconAarch64 = p => <Devicon icon='aarch64' release='2.16.0' {...p}/>
export const DeviconAdonisjs = p => <Devicon icon='adonisjs' release='2.16.0' {...p}/>
export const DeviconAftereffects = p => <Devicon icon='aftereffects' release='2.16.0' {...p}/>
export const DeviconAkka = p => <Devicon icon='akka' release='2.16.0' {...p}/>
export const DeviconAlgolia = p => <Devicon icon='algolia' release='2.16.0' {...p}/>
export const DeviconAlpinejs = p => <Devicon icon='alpinejs' release='2.16.0' {...p}/>
export const DeviconAmazonwebservices = p => <Devicon icon='amazonwebservices' release='2.16.0' {...p}/>
export const DeviconAnaconda = p => <Devicon icon='anaconda' release='2.16.0' {...p}/>
export const DeviconAndroid = p => <Devicon icon='android' release='2.16.0' {...p}/>
export const DeviconAndroidstudio = p => <Devicon icon='androidstudio' release='2.16.0' {...p}/>
export const DeviconAngular = p => <Devicon icon='angular' release='2.16.0' {...p}/>
export const DeviconAngularjs = p => <Devicon icon='angularjs' release='2.16.0' {...p}/>
export const DeviconAngularmaterial = p => <Devicon icon='angularmaterial' release='2.16.0' {...p}/>
export const DeviconAnsible = p => <Devicon icon='ansible' release='2.16.0' {...p}/>
export const DeviconAntdesign = p => <Devicon icon='antdesign' release='2.16.0' {...p}/>
export const DeviconApache = p => <Devicon icon='apache' release='2.16.0' {...p}/>
export const DeviconApacheairflow = p => <Devicon icon='apacheairflow' release='2.16.0' {...p}/>
export const DeviconApachekafka = p => <Devicon icon='apachekafka' release='2.16.0' {...p}/>
export const DeviconApachespark = p => <Devicon icon='apachespark' release='2.16.0' {...p}/>
export const DeviconApl = p => <Devicon icon='apl' release='2.16.0' {...p}/>
export const DeviconAppcelerator = p => <Devicon icon='appcelerator' release='2.16.0' {...p}/>
export const DeviconApple = p => <Devicon icon='apple' release='2.16.0' {...p}/>
export const DeviconAppwrite = p => <Devicon icon='appwrite' release='2.16.0' {...p}/>
export const DeviconArchlinux = p => <Devicon icon='archlinux' release='2.16.0' {...p}/>
export const DeviconArduino = p => <Devicon icon='arduino' release='2.16.0' {...p}/>
export const DeviconArgocd = p => <Devicon icon='argocd' release='2.16.0' {...p}/>
export const DeviconAstro = p => <Devicon icon='astro' release='2.16.0' {...p}/>
export const DeviconAtom = p => <Devicon icon='atom' release='2.16.0' {...p}/>
export const DeviconAwk = p => <Devicon icon='awk' release='2.16.0' {...p}/>
export const DeviconAxios = p => <Devicon icon='axios' release='2.16.0' {...p}/>
export const DeviconAzure = p => <Devicon icon='azure' release='2.16.0' {...p}/>
export const DeviconAzuredevops = p => <Devicon icon='azuredevops' release='2.16.0' {...p}/>
export const DeviconAzuresqldatabase = p => <Devicon icon='azuresqldatabase' release='2.16.0' {...p}/>
export const DeviconBabel = p => <Devicon icon='babel' release='2.16.0' {...p}/>
export const DeviconBackbonejs = p => <Devicon icon='backbonejs' release='2.16.0' {...p}/>
export const DeviconBallerina = p => <Devicon icon='ballerina' release='2.16.0' {...p}/>
export const DeviconBamboo = p => <Devicon icon='bamboo' release='2.16.0' {...p}/>
export const DeviconBash = p => <Devicon icon='bash' release='2.16.0' {...p}/>
export const DeviconBeats = p => <Devicon icon='beats' release='2.16.0' {...p}/>
export const DeviconBehance = p => <Devicon icon='behance' release='2.16.0' {...p}/>
export const DeviconBitbucket = p => <Devicon icon='bitbucket' release='2.16.0' {...p}/>
export const DeviconBlazor = p => <Devicon icon='blazor' release='2.16.0' {...p}/>
export const DeviconBlender = p => <Devicon icon='blender' release='2.16.0' {...p}/>
export const DeviconBootstrap = p => <Devicon icon='bootstrap' release='2.16.0' {...p}/>
export const DeviconBower = p => <Devicon icon='bower' release='2.16.0' {...p}/>
export const DeviconBrowserstack = p => <Devicon icon='browserstack' release='2.16.0' {...p}/>
export const DeviconBulma = p => <Devicon icon='bulma' release='2.16.0' {...p}/>
export const DeviconBun = p => <Devicon icon='bun' release='2.16.0' {...p}/>
export const DeviconC = p => <Devicon icon='c' release='2.16.0' {...p}/>
export const DeviconCairo = p => <Devicon icon='cairo' release='2.16.0' {...p}/>
export const DeviconCakephp = p => <Devicon icon='cakephp' release='2.16.0' {...p}/>
export const DeviconCanva = p => <Devicon icon='canva' release='2.16.0' {...p}/>
export const DeviconCapacitor = p => <Devicon icon='capacitor' release='2.16.0' {...p}/>
export const DeviconCarbon = p => <Devicon icon='carbon' release='2.16.0' {...p}/>
export const DeviconCassandra = p => <Devicon icon='cassandra' release='2.16.0' {...p}/>
export const DeviconCentos = p => <Devicon icon='centos' release='2.16.0' {...p}/>
export const DeviconCeylon = p => <Devicon icon='ceylon' release='2.16.0' {...p}/>
export const DeviconChrome = p => <Devicon icon='chrome' release='2.16.0' {...p}/>
export const DeviconCircleci = p => <Devicon icon='circleci' release='2.16.0' {...p}/>
export const DeviconClarity = p => <Devicon icon='clarity' release='2.16.0' {...p}/>
export const DeviconClion = p => <Devicon icon='clion' release='2.16.0' {...p}/>
export const DeviconClojure = p => <Devicon icon='clojure' release='2.16.0' {...p}/>
export const DeviconClojurescript = p => <Devicon icon='clojurescript' release='2.16.0' {...p}/>
export const DeviconCloudflare = p => <Devicon icon='cloudflare' release='2.16.0' {...p}/>
export const DeviconCloudflareworkers = p => <Devicon icon='cloudflareworkers' release='2.16.0' {...p}/>
export const DeviconCmake = p => <Devicon icon='cmake' release='2.16.0' {...p}/>
export const DeviconCodeac = p => <Devicon icon='codeac' release='2.16.0' {...p}/>
export const DeviconCodecov = p => <Devicon icon='codecov' release='2.16.0' {...p}/>
export const DeviconCodeigniter = p => <Devicon icon='codeigniter' release='2.16.0' {...p}/>
export const DeviconCodepen = p => <Devicon icon='codepen' release='2.16.0' {...p}/>
export const DeviconCoffeescript = p => <Devicon icon='coffeescript' release='2.16.0' {...p}/>
export const DeviconComposer = p => <Devicon icon='composer' release='2.16.0' {...p}/>
export const DeviconConfluence = p => <Devicon icon='confluence' release='2.16.0' {...p}/>
export const DeviconConsul = p => <Devicon icon='consul' release='2.16.0' {...p}/>
export const DeviconContao = p => <Devicon icon='contao' release='2.16.0' {...p}/>
export const DeviconCorejs = p => <Devicon icon='corejs' release='2.16.0' {...p}/>
export const DeviconCosmosdb = p => <Devicon icon='cosmosdb' release='2.16.0' {...p}/>
export const DeviconCouchbase = p => <Devicon icon='couchbase' release='2.16.0' {...p}/>
export const DeviconCouchdb = p => <Devicon icon='couchdb' release='2.16.0' {...p}/>
export const DeviconCplusplus = p => <Devicon icon='cplusplus' release='2.16.0' {...p}/>
export const DeviconCrystal = p => <Devicon icon='crystal' release='2.16.0' {...p}/>
export const DeviconCsharp = p => <Devicon icon='csharp' release='2.16.0' {...p}/>
export const DeviconCss3 = p => <Devicon icon='css3' release='2.16.0' {...p}/>
export const DeviconCucumber = p => <Devicon icon='cucumber' release='2.16.0' {...p}/>
export const DeviconCypressio = p => <Devicon icon='cypressio' release='2.16.0' {...p}/>
export const DeviconD3js = p => <Devicon icon='d3js' release='2.16.0' {...p}/>
export const DeviconDart = p => <Devicon icon='dart' release='2.16.0' {...p}/>
export const DeviconDatagrip = p => <Devicon icon='datagrip' release='2.16.0' {...p}/>
export const DeviconDataspell = p => <Devicon icon='dataspell' release='2.16.0' {...p}/>
export const DeviconDbeaver = p => <Devicon icon='dbeaver' release='2.16.0' {...p}/>
export const DeviconDebian = p => <Devicon icon='debian' release='2.16.0' {...p}/>
export const DeviconDenojs = p => <Devicon icon='denojs' release='2.16.0' {...p}/>
export const DeviconDevicon = p => <Devicon icon='devicon' release='2.16.0' {...p}/>
export const DeviconDigitalocean = p => <Devicon icon='digitalocean' release='2.16.0' {...p}/>
export const DeviconDiscordjs = p => <Devicon icon='discordjs' release='2.16.0' {...p}/>
export const DeviconDjango = p => <Devicon icon='django' release='2.16.0' {...p}/>
export const DeviconDjangorest = p => <Devicon icon='djangorest' release='2.16.0' {...p}/>
export const DeviconDocker = p => <Devicon icon='docker' release='2.16.0' {...p}/>
export const DeviconDoctrine = p => <Devicon icon='doctrine' release='2.16.0' {...p}/>
export const DeviconDotnet = p => <Devicon icon='dot-net' release='2.16.0' {...p}/>
export const DeviconDotnetcore = p => <Devicon icon='dotnetcore' release='2.16.0' {...p}/>
export const DeviconDreamweaver = p => <Devicon icon='dreamweaver' release='2.16.0' {...p}/>
export const DeviconDropwizard = p => <Devicon icon='dropwizard' release='2.16.0' {...p}/>
export const DeviconDrupal = p => <Devicon icon='drupal' release='2.16.0' {...p}/>
export const DeviconDynamodb = p => <Devicon icon='dynamodb' release='2.16.0' {...p}/>
export const DeviconEclipse = p => <Devicon icon='eclipse' release='2.16.0' {...p}/>
export const DeviconEcto = p => <Devicon icon='ecto' release='2.16.0' {...p}/>
export const DeviconElasticsearch = p => <Devicon icon='elasticsearch' release='2.16.0' {...p}/>
export const DeviconElectron = p => <Devicon icon='electron' release='2.16.0' {...p}/>
export const DeviconEleventy = p => <Devicon icon='eleventy' release='2.16.0' {...p}/>
export const DeviconElixir = p => <Devicon icon='elixir' release='2.16.0' {...p}/>
export const DeviconElm = p => <Devicon icon='elm' release='2.16.0' {...p}/>
export const DeviconEmacs = p => <Devicon icon='emacs' release='2.16.0' {...p}/>
export const DeviconEmbeddedc = p => <Devicon icon='embeddedc' release='2.16.0' {...p}/>
export const DeviconEmber = p => <Devicon icon='ember' release='2.16.0' {...p}/>
export const DeviconEnvoy = p => <Devicon icon='envoy' release='2.16.0' {...p}/>
export const DeviconErlang = p => <Devicon icon='erlang' release='2.16.0' {...p}/>
export const DeviconEslint = p => <Devicon icon='eslint' release='2.16.0' {...p}/>
export const DeviconExpress = p => <Devicon icon='express' release='2.16.0' {...p}/>
export const DeviconFacebook = p => <Devicon icon='facebook' release='2.16.0' {...p}/>
export const DeviconFastapi = p => <Devicon icon='fastapi' release='2.16.0' {...p}/>
export const DeviconFastify = p => <Devicon icon='fastify' release='2.16.0' {...p}/>
export const DeviconFaunadb = p => <Devicon icon='faunadb' release='2.16.0' {...p}/>
export const DeviconFeathersjs = p => <Devicon icon='feathersjs' release='2.16.0' {...p}/>
export const DeviconFedora = p => <Devicon icon='fedora' release='2.16.0' {...p}/>
export const DeviconFigma = p => <Devicon icon='figma' release='2.16.0' {...p}/>
export const DeviconFilezilla = p => <Devicon icon='filezilla' release='2.16.0' {...p}/>
export const DeviconFirebase = p => <Devicon icon='firebase' release='2.16.0' {...p}/>
export const DeviconFirefox = p => <Devicon icon='firefox' release='2.16.0' {...p}/>
export const DeviconFlask = p => <Devicon icon='flask' release='2.16.0' {...p}/>
export const DeviconFlutter = p => <Devicon icon='flutter' release='2.16.0' {...p}/>
export const DeviconFortran = p => <Devicon icon='fortran' release='2.16.0' {...p}/>
export const DeviconFoundation = p => <Devicon icon='foundation' release='2.16.0' {...p}/>
export const DeviconFramermotion = p => <Devicon icon='framermotion' release='2.16.0' {...p}/>
export const DeviconFramework7 = p => <Devicon icon='framework7' release='2.16.0' {...p}/>
export const DeviconFsharp = p => <Devicon icon='fsharp' release='2.16.0' {...p}/>
export const DeviconGatling = p => <Devicon icon='gatling' release='2.16.0' {...p}/>
export const DeviconGatsby = p => <Devicon icon='gatsby' release='2.16.0' {...p}/>
export const DeviconGazebo = p => <Devicon icon='gazebo' release='2.16.0' {...p}/>
export const DeviconGcc = p => <Devicon icon='gcc' release='2.16.0' {...p}/>
export const DeviconGentoo = p => <Devicon icon='gentoo' release='2.16.0' {...p}/>
export const DeviconGhost = p => <Devicon icon='ghost' release='2.16.0' {...p}/>
export const DeviconGimp = p => <Devicon icon='gimp' release='2.16.0' {...p}/>
export const DeviconGit = p => <Devicon icon='git' release='2.16.0' {...p}/>
export const DeviconGitbook = p => <Devicon icon='gitbook' release='2.16.0' {...p}/>
export const DeviconGithub = p => <Devicon icon='github' release='2.16.0' {...p}/>
export const DeviconGithubactions = p => <Devicon icon='githubactions' release='2.16.0' {...p}/>
export const DeviconGithubcodespaces = p => <Devicon icon='githubcodespaces' release='2.16.0' {...p}/>
export const DeviconGitlab = p => <Devicon icon='gitlab' release='2.16.0' {...p}/>
export const DeviconGitpod = p => <Devicon icon='gitpod' release='2.16.0' {...p}/>
export const DeviconGitter = p => <Devicon icon='gitter' release='2.16.0' {...p}/>
export const DeviconGo = p => <Devicon icon='go' release='2.16.0' {...p}/>
export const DeviconGodot = p => <Devicon icon='godot' release='2.16.0' {...p}/>
export const DeviconGoland = p => <Devicon icon='goland' release='2.16.0' {...p}/>
export const DeviconGoogle = p => <Devicon icon='google' release='2.16.0' {...p}/>
export const DeviconGooglecloud = p => <Devicon icon='googlecloud' release='2.16.0' {...p}/>
export const DeviconGradle = p => <Devicon icon='gradle' release='2.16.0' {...p}/>
export const DeviconGrafana = p => <Devicon icon='grafana' release='2.16.0' {...p}/>
export const DeviconGrails = p => <Devicon icon='grails' release='2.16.0' {...p}/>
export const DeviconGraphql = p => <Devicon icon='graphql' release='2.16.0' {...p}/>
export const DeviconGroovy = p => <Devicon icon='groovy' release='2.16.0' {...p}/>
export const DeviconGrpc = p => <Devicon icon='grpc' release='2.16.0' {...p}/>
export const DeviconGrunt = p => <Devicon icon='grunt' release='2.16.0' {...p}/>
export const DeviconGulp = p => <Devicon icon='gulp' release='2.16.0' {...p}/>
export const DeviconHadoop = p => <Devicon icon='hadoop' release='2.16.0' {...p}/>
export const DeviconHandlebars = p => <Devicon icon='handlebars' release='2.16.0' {...p}/>
export const DeviconHardhat = p => <Devicon icon='hardhat' release='2.16.0' {...p}/>
export const DeviconHarvester = p => <Devicon icon='harvester' release='2.16.0' {...p}/>
export const DeviconHaskell = p => <Devicon icon='haskell' release='2.16.0' {...p}/>
export const DeviconHaxe = p => <Devicon icon='haxe' release='2.16.0' {...p}/>
export const DeviconHelm = p => <Devicon icon='helm' release='2.16.0' {...p}/>
export const DeviconHeroku = p => <Devicon icon='heroku' release='2.16.0' {...p}/>
export const DeviconHibernate = p => <Devicon icon='hibernate' release='2.16.0' {...p}/>
export const DeviconHomebrew = p => <Devicon icon='homebrew' release='2.16.0' {...p}/>
export const DeviconHtml5 = p => <Devicon icon='html5' release='2.16.0' {...p}/>
export const DeviconHugo = p => <Devicon icon='hugo' release='2.16.0' {...p}/>
export const DeviconIe10 = p => <Devicon icon='ie10' release='2.16.0' {...p}/>
export const DeviconIfttt = p => <Devicon icon='ifttt' release='2.16.0' {...p}/>
export const DeviconIllustrator = p => <Devicon icon='illustrator' release='2.16.0' {...p}/>
export const DeviconInfluxdb = p => <Devicon icon='influxdb' release='2.16.0' {...p}/>
export const DeviconInkscape = p => <Devicon icon='inkscape' release='2.16.0' {...p}/>
export const DeviconInsomnia = p => <Devicon icon='insomnia' release='2.16.0' {...p}/>
export const DeviconIntellij = p => <Devicon icon='intellij' release='2.16.0' {...p}/>
export const DeviconIonic = p => <Devicon icon='ionic' release='2.16.0' {...p}/>
export const DeviconJaegertracing = p => <Devicon icon='jaegertracing' release='2.16.0' {...p}/>
export const DeviconJamstack = p => <Devicon icon='jamstack' release='2.16.0' {...p}/>
export const DeviconJasmine = p => <Devicon icon='jasmine' release='2.16.0' {...p}/>
export const DeviconJava = p => <Devicon icon='java' release='2.16.0' {...p}/>
export const DeviconJavascript = p => <Devicon icon='javascript' release='2.16.0' {...p}/>
export const DeviconJeet = p => <Devicon icon='jeet' release='2.16.0' {...p}/>
export const DeviconJekyll = p => <Devicon icon='jekyll' release='2.16.0' {...p}/>
export const DeviconJenkins = p => <Devicon icon='jenkins' release='2.16.0' {...p}/>
export const DeviconJest = p => <Devicon icon='jest' release='2.16.0' {...p}/>
export const DeviconJetbrains = p => <Devicon icon='jetbrains' release='2.16.0' {...p}/>
export const DeviconJetpackcompose = p => <Devicon icon='jetpackcompose' release='2.16.0' {...p}/>
export const DeviconJira = p => <Devicon icon='jira' release='2.16.0' {...p}/>
export const DeviconJiraalign = p => <Devicon icon='jiraalign' release='2.16.0' {...p}/>
export const DeviconJquery = p => <Devicon icon='jquery' release='2.16.0' {...p}/>
export const DeviconJson = p => <Devicon icon='json' release='2.16.0' {...p}/>
export const DeviconJule = p => <Devicon icon='jule' release='2.16.0' {...p}/>
export const DeviconJulia = p => <Devicon icon='julia' release='2.16.0' {...p}/>
export const DeviconJunit = p => <Devicon icon='junit' release='2.16.0' {...p}/>
export const DeviconJupyter = p => <Devicon icon='jupyter' release='2.16.0' {...p}/>
export const DeviconK3os = p => <Devicon icon='k3os' release='2.16.0' {...p}/>
export const DeviconK3s = p => <Devicon icon='k3s' release='2.16.0' {...p}/>
export const DeviconK6 = p => <Devicon icon='k6' release='2.16.0' {...p}/>
export const DeviconKaggle = p => <Devicon icon='kaggle' release='2.16.0' {...p}/>
export const DeviconKaratelabs = p => <Devicon icon='karatelabs' release='2.16.0' {...p}/>
export const DeviconKarma = p => <Devicon icon='karma' release='2.16.0' {...p}/>
export const DeviconKdeneon = p => <Devicon icon='kdeneon' release='2.16.0' {...p}/>
export const DeviconKeras = p => <Devicon icon='keras' release='2.16.0' {...p}/>
export const DeviconKibana = p => <Devicon icon='kibana' release='2.16.0' {...p}/>
export const DeviconKnexjs = p => <Devicon icon='knexjs' release='2.16.0' {...p}/>
export const DeviconKnockout = p => <Devicon icon='knockout' release='2.16.0' {...p}/>
export const DeviconKotlin = p => <Devicon icon='kotlin' release='2.16.0' {...p}/>
export const DeviconKrakenjs = p => <Devicon icon='krakenjs' release='2.16.0' {...p}/>
export const DeviconKtor = p => <Devicon icon='ktor' release='2.16.0' {...p}/>
export const DeviconKubernetes = p => <Devicon icon='kubernetes' release='2.16.0' {...p}/>
export const DeviconLabview = p => <Devicon icon='labview' release='2.16.0' {...p}/>
export const DeviconLaravel = p => <Devicon icon='laravel' release='2.16.0' {...p}/>
export const DeviconLatex = p => <Devicon icon='latex' release='2.16.0' {...p}/>
export const DeviconLess = p => <Devicon icon='less' release='2.16.0' {...p}/>
export const DeviconLinkedin = p => <Devicon icon='linkedin' release='2.16.0' {...p}/>
export const DeviconLinux = p => <Devicon icon='linux' release='2.16.0' {...p}/>
export const DeviconLiquibase = p => <Devicon icon='liquibase' release='2.16.0' {...p}/>
export const DeviconLivewire = p => <Devicon icon='livewire' release='2.16.0' {...p}/>
export const DeviconLlvm = p => <Devicon icon='llvm' release='2.16.0' {...p}/>
export const DeviconLodash = p => <Devicon icon='lodash' release='2.16.0' {...p}/>
export const DeviconLogstash = p => <Devicon icon='logstash' release='2.16.0' {...p}/>
export const DeviconLua = p => <Devicon icon='lua' release='2.16.0' {...p}/>
export const DeviconLumen = p => <Devicon icon='lumen' release='2.16.0' {...p}/>
export const DeviconMagento = p => <Devicon icon='magento' release='2.16.0' {...p}/>
export const DeviconMariadb = p => <Devicon icon='mariadb' release='2.16.0' {...p}/>
export const DeviconMarkdown = p => <Devicon icon='markdown' release='2.16.0' {...p}/>
export const DeviconMaterializecss = p => <Devicon icon='materializecss' release='2.16.0' {...p}/>
export const DeviconMaterialui = p => <Devicon icon='materialui' release='2.16.0' {...p}/>
export const DeviconMatlab = p => <Devicon icon='matlab' release='2.16.0' {...p}/>
export const DeviconMatplotlib = p => <Devicon icon='matplotlib' release='2.16.0' {...p}/>
export const DeviconMaven = p => <Devicon icon='maven' release='2.16.0' {...p}/>
export const DeviconMaya = p => <Devicon icon='maya' release='2.16.0' {...p}/>
export const DeviconMeteor = p => <Devicon icon='meteor' release='2.16.0' {...p}/>
export const DeviconMicrosoftsqlserver = p => <Devicon icon='microsoftsqlserver' release='2.16.0' {...p}/>
export const DeviconMinitab = p => <Devicon icon='minitab' release='2.16.0' {...p}/>
export const DeviconMithril = p => <Devicon icon='mithril' release='2.16.0' {...p}/>
export const DeviconMobx = p => <Devicon icon='mobx' release='2.16.0' {...p}/>
export const DeviconMocha = p => <Devicon icon='mocha' release='2.16.0' {...p}/>
export const DeviconModx = p => <Devicon icon='modx' release='2.16.0' {...p}/>
export const DeviconMoleculer = p => <Devicon icon='moleculer' release='2.16.0' {...p}/>
export const DeviconMongodb = p => <Devicon icon='mongodb' release='2.16.0' {...p}/>
export const DeviconMongoose = p => <Devicon icon='mongoose' release='2.16.0' {...p}/>
export const DeviconMoodle = p => <Devicon icon='moodle' release='2.16.0' {...p}/>
export const DeviconMsdos = p => <Devicon icon='msdos' release='2.16.0' {...p}/>
export const DeviconMysql = p => <Devicon icon='mysql' release='2.16.0' {...p}/>
export const DeviconNano = p => <Devicon icon='nano' release='2.16.0' {...p}/>
export const DeviconNeo4j = p => <Devicon icon='neo4j' release='2.16.0' {...p}/>
export const DeviconNeovim = p => <Devicon icon='neovim' release='2.16.0' {...p}/>
export const DeviconNestjs = p => <Devicon icon='nestjs' release='2.16.0' {...p}/>
export const DeviconNetlify = p => <Devicon icon='netlify' release='2.16.0' {...p}/>
export const DeviconNetworkx = p => <Devicon icon='networkx' release='2.16.0' {...p}/>
export const DeviconNextjs = p => <Devicon icon='nextjs' release='2.16.0' {...p}/>
export const DeviconNginx = p => <Devicon icon='nginx' release='2.16.0' {...p}/>
export const DeviconNgrx = p => <Devicon icon='ngrx' release='2.16.0' {...p}/>
export const DeviconNhibernate = p => <Devicon icon='nhibernate' release='2.16.0' {...p}/>
export const DeviconNim = p => <Devicon icon='nim' release='2.16.0' {...p}/>
export const DeviconNimble = p => <Devicon icon='nimble' release='2.16.0' {...p}/>
export const DeviconNixos = p => <Devicon icon='nixos' release='2.16.0' {...p}/>
export const DeviconNodejs = p => <Devicon icon='nodejs' release='2.16.0' {...p}/>
export const DeviconNodemon = p => <Devicon icon='nodemon' release='2.16.0' {...p}/>
export const DeviconNodewebkit = p => <Devicon icon='nodewebkit' release='2.16.0' {...p}/>
export const DeviconNomad = p => <Devicon icon='nomad' release='2.16.0' {...p}/>
export const DeviconNorg = p => <Devicon icon='norg' release='2.16.0' {...p}/>
export const DeviconNotion = p => <Devicon icon='notion' release='2.16.0' {...p}/>
export const DeviconNpm = p => <Devicon icon='npm' release='2.16.0' {...p}/>
export const DeviconNuget = p => <Devicon icon='nuget' release='2.16.0' {...p}/>
export const DeviconNumpy = p => <Devicon icon='numpy' release='2.16.0' {...p}/>
export const DeviconNuxtjs = p => <Devicon icon='nuxtjs' release='2.16.0' {...p}/>
export const DeviconOauth = p => <Devicon icon='oauth' release='2.16.0' {...p}/>
export const DeviconObjectivec = p => <Devicon icon='objectivec' release='2.16.0' {...p}/>
export const DeviconOcaml = p => <Devicon icon='ocaml' release='2.16.0' {...p}/>
export const DeviconOhmyzsh = p => <Devicon icon='ohmyzsh' release='2.16.0' {...p}/>
export const DeviconOkta = p => <Devicon icon='okta' release='2.16.0' {...p}/>
export const DeviconOpenal = p => <Devicon icon='openal' release='2.16.0' {...p}/>
export const DeviconOpenapi = p => <Devicon icon='openapi' release='2.16.0' {...p}/>
export const DeviconOpencl = p => <Devicon icon='opencl' release='2.16.0' {...p}/>
export const DeviconOpencv = p => <Devicon icon='opencv' release='2.16.0' {...p}/>
export const DeviconOpengl = p => <Devicon icon='opengl' release='2.16.0' {...p}/>
export const DeviconOpenstack = p => <Devicon icon='openstack' release='2.16.0' {...p}/>
export const DeviconOpensuse = p => <Devicon icon='opensuse' release='2.16.0' {...p}/>
export const DeviconOpentelemetry = p => <Devicon icon='opentelemetry' release='2.16.0' {...p}/>
export const DeviconOpera = p => <Devicon icon='opera' release='2.16.0' {...p}/>
export const DeviconOracle = p => <Devicon icon='oracle' release='2.16.0' {...p}/>
export const DeviconOry = p => <Devicon icon='ory' release='2.16.0' {...p}/>
export const DeviconP5js = p => <Devicon icon='p5js' release='2.16.0' {...p}/>
export const DeviconPacker = p => <Devicon icon='packer' release='2.16.0' {...p}/>
export const DeviconPandas = p => <Devicon icon='pandas' release='2.16.0' {...p}/>
export const DeviconPerl = p => <Devicon icon='perl' release='2.16.0' {...p}/>
export const DeviconPfsense = p => <Devicon icon='pfsense' release='2.16.0' {...p}/>
export const DeviconPhalcon = p => <Devicon icon='phalcon' release='2.16.0' {...p}/>
export const DeviconPhoenix = p => <Devicon icon='phoenix' release='2.16.0' {...p}/>
export const DeviconPhotonengine = p => <Devicon icon='photonengine' release='2.16.0' {...p}/>
export const DeviconPhotoshop = p => <Devicon icon='photoshop' release='2.16.0' {...p}/>
export const DeviconPhp = p => <Devicon icon='php' release='2.16.0' {...p}/>
export const DeviconPhpstorm = p => <Devicon icon='phpstorm' release='2.16.0' {...p}/>
export const DeviconPlaywright = p => <Devicon icon='playwright' release='2.16.0' {...p}/>
export const DeviconPlotly = p => <Devicon icon='plotly' release='2.16.0' {...p}/>
export const DeviconPnpm = p => <Devicon icon='pnpm' release='2.16.0' {...p}/>
export const DeviconPodman = p => <Devicon icon='podman' release='2.16.0' {...p}/>
export const DeviconPoetry = p => <Devicon icon='poetry' release='2.16.0' {...p}/>
export const DeviconPolygon = p => <Devicon icon='polygon' release='2.16.0' {...p}/>
export const DeviconPortainer = p => <Devicon icon='portainer' release='2.16.0' {...p}/>
export const DeviconPostcss = p => <Devicon icon='postcss' release='2.16.0' {...p}/>
export const DeviconPostgresql = p => <Devicon icon='postgresql' release='2.16.0' {...p}/>
export const DeviconPostman = p => <Devicon icon='postman' release='2.16.0' {...p}/>
export const DeviconPowershell = p => <Devicon icon='powershell' release='2.16.0' {...p}/>
export const DeviconPremierepro = p => <Devicon icon='premierepro' release='2.16.0' {...p}/>
export const DeviconPrisma = p => <Devicon icon='prisma' release='2.16.0' {...p}/>
export const DeviconProcessing = p => <Devicon icon='processing' release='2.16.0' {...p}/>
export const DeviconProlog = p => <Devicon icon='prolog' release='2.16.0' {...p}/>
export const DeviconPrometheus = p => <Devicon icon='prometheus' release='2.16.0' {...p}/>
export const DeviconProtractor = p => <Devicon icon='protractor' release='2.16.0' {...p}/>
export const DeviconPulsar = p => <Devicon icon='pulsar' release='2.16.0' {...p}/>
export const DeviconPulumi = p => <Devicon icon='pulumi' release='2.16.0' {...p}/>
export const DeviconPuppeteer = p => <Devicon icon='puppeteer' release='2.16.0' {...p}/>
export const DeviconPurescript = p => <Devicon icon='purescript' release='2.16.0' {...p}/>
export const DeviconPutty = p => <Devicon icon='putty' release='2.16.0' {...p}/>
export const DeviconPycharm = p => <Devicon icon='pycharm' release='2.16.0' {...p}/>
export const DeviconPypi = p => <Devicon icon='pypi' release='2.16.0' {...p}/>
export const DeviconPyscript = p => <Devicon icon='pyscript' release='2.16.0' {...p}/>
export const DeviconPytest = p => <Devicon icon='pytest' release='2.16.0' {...p}/>
export const DeviconPython = p => <Devicon icon='python' release='2.16.0' {...p}/>
export const DeviconPytorch = p => <Devicon icon='pytorch' release='2.16.0' {...p}/>
export const DeviconQodana = p => <Devicon icon='qodana' release='2.16.0' {...p}/>
export const DeviconQt = p => <Devicon icon='qt' release='2.16.0' {...p}/>
export const DeviconQuarkus = p => <Devicon icon='quarkus' release='2.16.0' {...p}/>
export const DeviconQuasar = p => <Devicon icon='quasar' release='2.16.0' {...p}/>
export const DeviconQwik = p => <Devicon icon='qwik' release='2.16.0' {...p}/>
export const DeviconR = p => <Devicon icon='r' release='2.16.0' {...p}/>
export const DeviconRabbitmq = p => <Devicon icon='rabbitmq' release='2.16.0' {...p}/>
export const DeviconRails = p => <Devicon icon='rails' release='2.16.0' {...p}/>
export const DeviconRailway = p => <Devicon icon='railway' release='2.16.0' {...p}/>
export const DeviconRancher = p => <Devicon icon='rancher' release='2.16.0' {...p}/>
export const DeviconRaspberrypi = p => <Devicon icon='raspberrypi' release='2.16.0' {...p}/>
export const DeviconReach = p => <Devicon icon='reach' release='2.16.0' {...p}/>
export const DeviconReact = p => <Devicon icon='react' release='2.16.0' {...p}/>
export const DeviconReactbootstrap = p => <Devicon icon='reactbootstrap' release='2.16.0' {...p}/>
export const DeviconReactnavigation = p => <Devicon icon='reactnavigation' release='2.16.0' {...p}/>
export const DeviconReadthedocs = p => <Devicon icon='readthedocs' release='2.16.0' {...p}/>
export const DeviconRealm = p => <Devicon icon='realm' release='2.16.0' {...p}/>
export const DeviconRect = p => <Devicon icon='rect' release='2.16.0' {...p}/>
export const DeviconRedhat = p => <Devicon icon='redhat' release='2.16.0' {...p}/>
export const DeviconRedis = p => <Devicon icon='redis' release='2.16.0' {...p}/>
export const DeviconRedux = p => <Devicon icon='redux' release='2.16.0' {...p}/>
export const DeviconRenpy = p => <Devicon icon='renpy' release='2.16.0' {...p}/>
export const DeviconReplit = p => <Devicon icon='replit' release='2.16.0' {...p}/>
export const DeviconRider = p => <Devicon icon='rider' release='2.16.0' {...p}/>
export const DeviconRocksdb = p => <Devicon icon='rocksdb' release='2.16.0' {...p}/>
export const DeviconRockylinux = p => <Devicon icon='rockylinux' release='2.16.0' {...p}/>
export const DeviconRollup = p => <Devicon icon='rollup' release='2.16.0' {...p}/>
export const DeviconRos = p => <Devicon icon='ros' release='2.16.0' {...p}/>
export const DeviconRspec = p => <Devicon icon='rspec' release='2.16.0' {...p}/>
export const DeviconRstudio = p => <Devicon icon='rstudio' release='2.16.0' {...p}/>
export const DeviconRuby = p => <Devicon icon='ruby' release='2.16.0' {...p}/>
export const DeviconRubymine = p => <Devicon icon='rubymine' release='2.16.0' {...p}/>
export const DeviconRust = p => <Devicon icon='rust' release='2.16.0' {...p}/>
export const DeviconRxjs = p => <Devicon icon='rxjs' release='2.16.0' {...p}/>
export const DeviconSafari = p => <Devicon icon='safari' release='2.16.0' {...p}/>
export const DeviconSalesforce = p => <Devicon icon='salesforce' release='2.16.0' {...p}/>
export const DeviconSanity = p => <Devicon icon='sanity' release='2.16.0' {...p}/>
export const DeviconSass = p => <Devicon icon='sass' release='2.16.0' {...p}/>
export const DeviconScala = p => <Devicon icon='scala' release='2.16.0' {...p}/>
export const DeviconScalingo = p => <Devicon icon='scalingo' release='2.16.0' {...p}/>
export const DeviconScikitlearn = p => <Devicon icon='scikitlearn' release='2.16.0' {...p}/>
export const DeviconSdl = p => <Devicon icon='sdl' release='2.16.0' {...p}/>
export const DeviconSelenium = p => <Devicon icon='selenium' release='2.16.0' {...p}/>
export const DeviconSema = p => <Devicon icon='sema' release='2.16.0' {...p}/>
export const DeviconSentry = p => <Devicon icon='sentry' release='2.16.0' {...p}/>
export const DeviconReactrouter = p => <Devicon icon='reactrouter' release='2.16.0' {...p}/>
export const DeviconSequelize = p => <Devicon icon='sequelize' release='2.16.0' {...p}/>
export const DeviconShopware = p => <Devicon icon='shopware' release='2.16.0' {...p}/>
export const DeviconShotgrid = p => <Devicon icon='shotgrid' release='2.16.0' {...p}/>
export const DeviconSketch = p => <Devicon icon='sketch' release='2.16.0' {...p}/>
export const DeviconSlack = p => <Devicon icon='slack' release='2.16.0' {...p}/>
export const DeviconSocketio = p => <Devicon icon='socketio' release='2.16.0' {...p}/>
export const DeviconSolidity = p => <Devicon icon='solidity' release='2.16.0' {...p}/>
export const DeviconSolidjs = p => <Devicon icon='solidjs' release='2.16.0' {...p}/>
export const DeviconSonarqube = p => <Devicon icon='sonarqube' release='2.16.0' {...p}/>
export const DeviconSourcetree = p => <Devicon icon='sourcetree' release='2.16.0' {...p}/>
export const DeviconSpack = p => <Devicon icon='spack' release='2.16.0' {...p}/>
export const DeviconSplunk = p => <Devicon icon='splunk' release='2.16.0' {...p}/>
export const DeviconSpring = p => <Devicon icon='spring' release='2.16.0' {...p}/>
export const DeviconSpss = p => <Devicon icon='spss' release='2.16.0' {...p}/>
export const DeviconSpyder = p => <Devicon icon='spyder' release='2.16.0' {...p}/>
export const DeviconSqlalchemy = p => <Devicon icon='sqlalchemy' release='2.16.0' {...p}/>
export const DeviconSqldeveloper = p => <Devicon icon='sqldeveloper' release='2.16.0' {...p}/>
export const DeviconSqlite = p => <Devicon icon='sqlite' release='2.16.0' {...p}/>
export const DeviconSsh = p => <Devicon icon='ssh' release='2.16.0' {...p}/>
export const DeviconStackoverflow = p => <Devicon icon='stackoverflow' release='2.16.0' {...p}/>
export const DeviconStata = p => <Devicon icon='stata' release='2.16.0' {...p}/>
export const DeviconStorybook = p => <Devicon icon='storybook' release='2.16.0' {...p}/>
export const DeviconStreamlit = p => <Devicon icon='streamlit' release='2.16.0' {...p}/>
export const DeviconStylus = p => <Devicon icon='stylus' release='2.16.0' {...p}/>
export const DeviconSubversion = p => <Devicon icon='subversion' release='2.16.0' {...p}/>
export const DeviconSupabase = p => <Devicon icon='supabase' release='2.16.0' {...p}/>
export const DeviconSvelte = p => <Devicon icon='svelte' release='2.16.0' {...p}/>
export const DeviconSwagger = p => <Devicon icon='swagger' release='2.16.0' {...p}/>
export const DeviconSwift = p => <Devicon icon='swift' release='2.16.0' {...p}/>
export const DeviconSwiper = p => <Devicon icon='swiper' release='2.16.0' {...p}/>
export const DeviconSymfony = p => <Devicon icon='symfony' release='2.16.0' {...p}/>
export const DeviconTailwindcss = p => <Devicon icon='tailwindcss' release='2.16.0' {...p}/>
export const DeviconTauri = p => <Devicon icon='tauri' release='2.16.0' {...p}/>
export const DeviconTensorflow = p => <Devicon icon='tensorflow' release='2.16.0' {...p}/>
export const DeviconTerraform = p => <Devicon icon='terraform' release='2.16.0' {...p}/>
export const DeviconTex = p => <Devicon icon='tex' release='2.16.0' {...p}/>
export const DeviconThealgorithms = p => <Devicon icon='thealgorithms' release='2.16.0' {...p}/>
export const DeviconThreejs = p => <Devicon icon='threejs' release='2.16.0' {...p}/>
export const DeviconTitaniumsdk = p => <Devicon icon='titaniumsdk' release='2.16.0' {...p}/>
export const DeviconTomcat = p => <Devicon icon='tomcat' release='2.16.0' {...p}/>
export const DeviconTortoisegit = p => <Devicon icon='tortoisegit' release='2.16.0' {...p}/>
export const DeviconTowergit = p => <Devicon icon='towergit' release='2.16.0' {...p}/>
export const DeviconTraefikmesh = p => <Devicon icon='traefikmesh' release='2.16.0' {...p}/>
export const DeviconTraefikproxy = p => <Devicon icon='traefikproxy' release='2.16.0' {...p}/>
export const DeviconTravis = p => <Devicon icon='travis' release='2.16.0' {...p}/>
export const DeviconTrello = p => <Devicon icon='trello' release='2.16.0' {...p}/>
export const DeviconTrpc = p => <Devicon icon='trpc' release='2.16.0' {...p}/>
export const DeviconTwitter = p => <Devicon icon='twitter' release='2.16.0' {...p}/>
export const DeviconTypescript = p => <Devicon icon='typescript' release='2.16.0' {...p}/>
export const DeviconTypo3 = p => <Devicon icon='typo3' release='2.16.0' {...p}/>
export const DeviconUbuntu = p => <Devicon icon='ubuntu' release='2.16.0' {...p}/>
export const DeviconUnifiedmodelinglanguage = p => <Devicon icon='unifiedmodelinglanguage' release='2.16.0' {...p}/>
export const DeviconUnity = p => <Devicon icon='unity' release='2.16.0' {...p}/>
export const DeviconUnix = p => <Devicon icon='unix' release='2.16.0' {...p}/>
export const DeviconUnrealengine = p => <Devicon icon='unrealengine' release='2.16.0' {...p}/>
export const DeviconUwsgi = p => <Devicon icon='uwsgi' release='2.16.0' {...p}/>
export const DeviconV8 = p => <Devicon icon='v8' release='2.16.0' {...p}/>
export const DeviconVagrant = p => <Devicon icon='vagrant' release='2.16.0' {...p}/>
export const DeviconVala = p => <Devicon icon='vala' release='2.16.0' {...p}/>
export const DeviconVault = p => <Devicon icon='vault' release='2.16.0' {...p}/>
export const DeviconVercel = p => <Devicon icon='vercel' release='2.16.0' {...p}/>
export const DeviconVertx = p => <Devicon icon='vertx' release='2.16.0' {...p}/>
export const DeviconVim = p => <Devicon icon='vim' release='2.16.0' {...p}/>
export const DeviconVisualbasic = p => <Devicon icon='visualbasic' release='2.16.0' {...p}/>
export const DeviconVisualstudio = p => <Devicon icon='visualstudio' release='2.16.0' {...p}/>
export const DeviconVite = p => <Devicon icon='vite' release='2.16.0' {...p}/>
export const DeviconVitejs = p => <Devicon icon='vitejs' release='2.16.0' {...p}/>
export const DeviconVitess = p => <Devicon icon='vitess' release='2.16.0' {...p}/>
export const DeviconVitest = p => <Devicon icon='vitest' release='2.16.0' {...p}/>
export const DeviconVscode = p => <Devicon icon='vscode' release='2.16.0' {...p}/>
export const DeviconVsphere = p => <Devicon icon='vsphere' release='2.16.0' {...p}/>
export const DeviconVuejs = p => <Devicon icon='vuejs' release='2.16.0' {...p}/>
export const DeviconVuestorefront = p => <Devicon icon='vuestorefront' release='2.16.0' {...p}/>
export const DeviconVuetify = p => <Devicon icon='vuetify' release='2.16.0' {...p}/>
export const DeviconVyper = p => <Devicon icon='vyper' release='2.16.0' {...p}/>
export const DeviconWasm = p => <Devicon icon='wasm' release='2.16.0' {...p}/>
export const DeviconWebflow = p => <Devicon icon='webflow' release='2.16.0' {...p}/>
export const DeviconWeblate = p => <Devicon icon='weblate' release='2.16.0' {...p}/>
export const DeviconWebpack = p => <Devicon icon='webpack' release='2.16.0' {...p}/>
export const DeviconWebstorm = p => <Devicon icon='webstorm' release='2.16.0' {...p}/>
export const DeviconWindows11 = p => <Devicon icon='windows11' release='2.16.0' {...p}/>
export const DeviconWindows8 = p => <Devicon icon='windows8' release='2.16.0' {...p}/>
export const DeviconWoocommerce = p => <Devicon icon='woocommerce' release='2.16.0' {...p}/>
export const DeviconWordpress = p => <Devicon icon='wordpress' release='2.16.0' {...p}/>
export const DeviconXamarin = p => <Devicon icon='xamarin' release='2.16.0' {...p}/>
export const DeviconXcode = p => <Devicon icon='xcode' release='2.16.0' {...p}/>
export const DeviconXd = p => <Devicon icon='xd' release='2.16.0' {...p}/>
export const DeviconXml = p => <Devicon icon='xml' release='2.16.0' {...p}/>
export const DeviconYaml = p => <Devicon icon='yaml' release='2.16.0' {...p}/>
export const DeviconYarn = p => <Devicon icon='yarn' release='2.16.0' {...p}/>
export const DeviconYii = p => <Devicon icon='yii' release='2.16.0' {...p}/>
export const DeviconYugabytedb = p => <Devicon icon='yugabytedb' release='2.16.0' {...p}/>
export const DeviconYunohost = p => <Devicon icon='yunohost' release='2.16.0' {...p}/>
export const DeviconZend = p => <Devicon icon='zend' release='2.16.0' {...p}/>
export const DeviconZig = p => <Devicon icon='zig' release='2.16.0' {...p}/>
