import Devicon from '../devicon'
export const DeviconAftereffects = p => <Devicon icon='aftereffects' release='2.7' {...p}/>
export const DeviconAmazonwebservices = p => <Devicon icon='amazonwebservices' release='2.7' {...p}/>
export const DeviconAndroid = p => <Devicon icon='android' release='2.7' {...p}/>
export const DeviconAngularjs = p => <Devicon icon='angularjs' release='2.7' {...p}/>
export const DeviconApache = p => <Devicon icon='apache' release='2.7' {...p}/>
export const DeviconAppcelerator = p => <Devicon icon='appcelerator' release='2.7' {...p}/>
export const DeviconApple = p => <Devicon icon='apple' release='2.7' {...p}/>
export const DeviconAtom = p => <Devicon icon='atom' release='2.7' {...p}/>
export const DeviconBabel = p => <Devicon icon='babel' release='2.7' {...p}/>
export const DeviconBackbonejs = p => <Devicon icon='backbonejs' release='2.7' {...p}/>
export const DeviconBehance = p => <Devicon icon='behance' release='2.7' {...p}/>
export const DeviconBitbucket = p => <Devicon icon='bitbucket' release='2.7' {...p}/>
export const DeviconBootstrap = p => <Devicon icon='bootstrap' release='2.7' {...p}/>
export const DeviconBower = p => <Devicon icon='bower' release='2.7' {...p}/>
export const DeviconC = p => <Devicon icon='c' release='2.7' {...p}/>
export const DeviconCakephp = p => <Devicon icon='cakephp' release='2.7' {...p}/>
export const DeviconCeylon = p => <Devicon icon='ceylon' release='2.7' {...p}/>
export const DeviconChrome = p => <Devicon icon='chrome' release='2.7' {...p}/>
export const DeviconClojure = p => <Devicon icon='clojure' release='2.7' {...p}/>
export const DeviconClojurescript = p => <Devicon icon='clojurescript' release='2.7' {...p}/>
export const DeviconCodeigniter = p => <Devicon icon='codeigniter' release='2.7' {...p}/>
export const DeviconCodepen = p => <Devicon icon='codepen' release='2.7' {...p}/>
export const DeviconCoffeescript = p => <Devicon icon='coffeescript' release='2.7' {...p}/>
export const DeviconComposer = p => <Devicon icon='composer' release='2.7' {...p}/>
export const DeviconConfluence = p => <Devicon icon='confluence' release='2.7' {...p}/>
export const DeviconCouchdb = p => <Devicon icon='couchdb' release='2.7' {...p}/>
export const DeviconCplusplus = p => <Devicon icon='cplusplus' release='2.7' {...p}/>
export const DeviconCsharp = p => <Devicon icon='csharp' release='2.7' {...p}/>
export const DeviconCss3 = p => <Devicon icon='css3' release='2.7' {...p}/>
export const DeviconCucumber = p => <Devicon icon='cucumber' release='2.7' {...p}/>
export const DeviconD3js = p => <Devicon icon='d3js' release='2.7' {...p}/>
export const DeviconDebian = p => <Devicon icon='debian' release='2.7' {...p}/>
export const DeviconDevicon = p => <Devicon icon='devicon' release='2.7' {...p}/>
export const DeviconDjango = p => <Devicon icon='django' release='2.7' {...p}/>
export const DeviconDocker = p => <Devicon icon='docker' release='2.7' {...p}/>
export const DeviconDoctrine = p => <Devicon icon='doctrine' release='2.7' {...p}/>
export const DeviconDotnet = p => <Devicon icon='dot-net' release='2.7' {...p}/>
export const DeviconDrupal = p => <Devicon icon='drupal' release='2.7' {...p}/>
export const DeviconElectron = p => <Devicon icon='electron' release='2.7' {...p}/>
export const DeviconElm = p => <Devicon icon='elm' release='2.7' {...p}/>
export const DeviconEmber = p => <Devicon icon='ember' release='2.7' {...p}/>
export const DeviconErlang = p => <Devicon icon='erlang' release='2.7' {...p}/>
export const DeviconExpress = p => <Devicon icon='express' release='2.7' {...p}/>
export const DeviconFacebook = p => <Devicon icon='facebook' release='2.7' {...p}/>
export const DeviconFirefox = p => <Devicon icon='firefox' release='2.7' {...p}/>
export const DeviconFlutter = p => <Devicon icon='flutter' release='2.7' {...p}/>
export const DeviconFoundation = p => <Devicon icon='foundation' release='2.7' {...p}/>
export const DeviconGatling = p => <Devicon icon='gatling' release='2.7' {...p}/>
export const DeviconGatsby = p => <Devicon icon='gatsby' release='2.7' {...p}/>
export const DeviconGimp = p => <Devicon icon='gimp' release='2.7' {...p}/>
export const DeviconGit = p => <Devicon icon='git' release='2.7' {...p}/>
export const DeviconGithub = p => <Devicon icon='github' release='2.7' {...p}/>
export const DeviconGitlab = p => <Devicon icon='gitlab' release='2.7' {...p}/>
export const DeviconGo = p => <Devicon icon='go' release='2.7' {...p}/>
export const DeviconGoogle = p => <Devicon icon='google' release='2.7' {...p}/>
export const DeviconGradle = p => <Devicon icon='gradle' release='2.7' {...p}/>
export const DeviconGrails = p => <Devicon icon='grails' release='2.7' {...p}/>
export const DeviconGroovy = p => <Devicon icon='groovy' release='2.7' {...p}/>
export const DeviconGrunt = p => <Devicon icon='grunt' release='2.7' {...p}/>
export const DeviconGulp = p => <Devicon icon='gulp' release='2.7' {...p}/>
export const DeviconHandlebars = p => <Devicon icon='handlebars' release='2.7' {...p}/>
export const DeviconHaskell = p => <Devicon icon='haskell' release='2.7' {...p}/>
export const DeviconHaxe = p => <Devicon icon='haxe' release='2.7' {...p}/>
export const DeviconHeroku = p => <Devicon icon='heroku' release='2.7' {...p}/>
export const DeviconHtml5 = p => <Devicon icon='html5' release='2.7' {...p}/>
export const DeviconIe10 = p => <Devicon icon='ie10' release='2.7' {...p}/>
export const DeviconIllustrator = p => <Devicon icon='illustrator' release='2.7' {...p}/>
export const DeviconInkscape = p => <Devicon icon='inkscape' release='2.7' {...p}/>
export const DeviconIntellij = p => <Devicon icon='intellij' release='2.7' {...p}/>
export const DeviconIonic = p => <Devicon icon='ionic' release='2.7' {...p}/>
export const DeviconJasmine = p => <Devicon icon='jasmine' release='2.7' {...p}/>
export const DeviconJava = p => <Devicon icon='java' release='2.7' {...p}/>
export const DeviconJavascript = p => <Devicon icon='javascript' release='2.7' {...p}/>
export const DeviconJeet = p => <Devicon icon='jeet' release='2.7' {...p}/>
export const DeviconJenkins = p => <Devicon icon='jenkins' release='2.7' {...p}/>
export const DeviconJetbrains = p => <Devicon icon='jetbrains' release='2.7' {...p}/>
export const DeviconJquery = p => <Devicon icon='jquery' release='2.7' {...p}/>
export const DeviconKotlin = p => <Devicon icon='kotlin' release='2.7' {...p}/>
export const DeviconKrakenjs = p => <Devicon icon='krakenjs' release='2.7' {...p}/>
export const DeviconLaravel = p => <Devicon icon='laravel' release='2.7' {...p}/>
export const DeviconLess = p => <Devicon icon='less' release='2.7' {...p}/>
export const DeviconLinkedin = p => <Devicon icon='linkedin' release='2.7' {...p}/>
export const DeviconLinux = p => <Devicon icon='linux' release='2.7' {...p}/>
export const DeviconMaterialui = p => <Devicon icon='materialui' release='2.7' {...p}/>
export const DeviconMeteor = p => <Devicon icon='meteor' release='2.7' {...p}/>
export const DeviconMocha = p => <Devicon icon='mocha' release='2.7' {...p}/>
export const DeviconMongodb = p => <Devicon icon='mongodb' release='2.7' {...p}/>
export const DeviconMoodle = p => <Devicon icon='moodle' release='2.7' {...p}/>
export const DeviconMysql = p => <Devicon icon='mysql' release='2.7' {...p}/>
export const DeviconNestjs = p => <Devicon icon='nestjs' release='2.7' {...p}/>
export const DeviconNginx = p => <Devicon icon='nginx' release='2.7' {...p}/>
export const DeviconNodejs = p => <Devicon icon='nodejs' release='2.7' {...p}/>
export const DeviconNodewebkit = p => <Devicon icon='nodewebkit' release='2.7' {...p}/>
export const DeviconNpm = p => <Devicon icon='npm' release='2.7' {...p}/>
export const DeviconOracle = p => <Devicon icon='oracle' release='2.7' {...p}/>
export const DeviconPhotoshop = p => <Devicon icon='photoshop' release='2.7' {...p}/>
export const DeviconPhp = p => <Devicon icon='php' release='2.7' {...p}/>
export const DeviconPhpstorm = p => <Devicon icon='phpstorm' release='2.7' {...p}/>
export const DeviconPostgresql = p => <Devicon icon='postgresql' release='2.7' {...p}/>
export const DeviconPremierepro = p => <Devicon icon='premierepro' release='2.7' {...p}/>
export const DeviconProtractor = p => <Devicon icon='protractor' release='2.7' {...p}/>
export const DeviconPycharm = p => <Devicon icon='pycharm' release='2.7' {...p}/>
export const DeviconPython = p => <Devicon icon='python' release='2.7' {...p}/>
export const DeviconRails = p => <Devicon icon='rails' release='2.7' {...p}/>
export const DeviconReact = p => <Devicon icon='react' release='2.7' {...p}/>
export const DeviconRedhat = p => <Devicon icon='redhat' release='2.7' {...p}/>
export const DeviconRedis = p => <Devicon icon='redis' release='2.7' {...p}/>
export const DeviconRedux = p => <Devicon icon='redux' release='2.7' {...p}/>
export const DeviconRuby = p => <Devicon icon='ruby' release='2.7' {...p}/>
export const DeviconRubymine = p => <Devicon icon='rubymine' release='2.7' {...p}/>
export const DeviconRust = p => <Devicon icon='rust' release='2.7' {...p}/>
export const DeviconSafari = p => <Devicon icon='safari' release='2.7' {...p}/>
export const DeviconSass = p => <Devicon icon='sass' release='2.7' {...p}/>
export const DeviconScala = p => <Devicon icon='scala' release='2.7' {...p}/>
export const DeviconSequelize = p => <Devicon icon='sequelize' release='2.7' {...p}/>
export const DeviconSketch = p => <Devicon icon='sketch' release='2.7' {...p}/>
export const DeviconSlack = p => <Devicon icon='slack' release='2.7' {...p}/>
export const DeviconSourcetree = p => <Devicon icon='sourcetree' release='2.7' {...p}/>
export const DeviconSsh = p => <Devicon icon='ssh' release='2.7' {...p}/>
export const DeviconStylus = p => <Devicon icon='stylus' release='2.7' {...p}/>
export const DeviconSwift = p => <Devicon icon='swift' release='2.7' {...p}/>
export const DeviconSymfony = p => <Devicon icon='symfony' release='2.7' {...p}/>
export const DeviconTomcat = p => <Devicon icon='tomcat' release='2.7' {...p}/>
export const DeviconTravis = p => <Devicon icon='travis' release='2.7' {...p}/>
export const DeviconTrello = p => <Devicon icon='trello' release='2.7' {...p}/>
export const DeviconTwitter = p => <Devicon icon='twitter' release='2.7' {...p}/>
export const DeviconTypescript = p => <Devicon icon='typescript' release='2.7' {...p}/>
export const DeviconTypo3 = p => <Devicon icon='typo3' release='2.7' {...p}/>
export const DeviconUbuntu = p => <Devicon icon='ubuntu' release='2.7' {...p}/>
export const DeviconVagrant = p => <Devicon icon='vagrant' release='2.7' {...p}/>
export const DeviconVim = p => <Devicon icon='vim' release='2.7' {...p}/>
export const DeviconVisualstudio = p => <Devicon icon='visualstudio' release='2.7' {...p}/>
export const DeviconVuejs = p => <Devicon icon='vuejs' release='2.7' {...p}/>
export const DeviconWebpack = p => <Devicon icon='webpack' release='2.7' {...p}/>
export const DeviconWebstorm = p => <Devicon icon='webstorm' release='2.7' {...p}/>
export const DeviconWindows8 = p => <Devicon icon='windows8' release='2.7' {...p}/>
export const DeviconWoocommerce = p => <Devicon icon='woocommerce' release='2.7' {...p}/>
export const DeviconWordpress = p => <Devicon icon='wordpress' release='2.7' {...p}/>
export const DeviconYarn = p => <Devicon icon='yarn' release='2.7' {...p}/>
export const DeviconYii = p => <Devicon icon='yii' release='2.7' {...p}/>
export const DeviconYunohost = p => <Devicon icon='yunohost' release='2.7' {...p}/>
export const DeviconZend = p => <Devicon icon='zend' release='2.7' {...p}/>
