import PartialProps from '../types'
export function DeviconAftereffects(p: PartialProps): React.JSX.Element
export function DeviconAmazonwebservices(p: PartialProps): React.JSX.Element
export function DeviconAndroid(p: PartialProps): React.JSX.Element
export function DeviconAngularjs(p: PartialProps): React.JSX.Element
export function DeviconApache(p: PartialProps): React.JSX.Element
export function DeviconAppcelerator(p: PartialProps): React.JSX.Element
export function DeviconApple(p: PartialProps): React.JSX.Element
export function DeviconAppwrite(p: PartialProps): React.JSX.Element
export function DeviconAtom(p: PartialProps): React.JSX.Element
export function DeviconBabel(p: PartialProps): React.JSX.Element
export function DeviconBackbonejs(p: PartialProps): React.JSX.Element
export function DeviconBash(p: PartialProps): React.JSX.Element
export function DeviconBehance(p: PartialProps): React.JSX.Element
export function DeviconBitbucket(p: PartialProps): React.JSX.Element
export function DeviconBootstrap(p: PartialProps): React.JSX.Element
export function DeviconBower(p: PartialProps): React.JSX.Element
export function DeviconC(p: PartialProps): React.JSX.Element
export function DeviconCakephp(p: PartialProps): React.JSX.Element
export function DeviconCeylon(p: PartialProps): React.JSX.Element
export function DeviconChrome(p: PartialProps): React.JSX.Element
export function DeviconClojure(p: PartialProps): React.JSX.Element
export function DeviconClojurescript(p: PartialProps): React.JSX.Element
export function DeviconCodeigniter(p: PartialProps): React.JSX.Element
export function DeviconCodepen(p: PartialProps): React.JSX.Element
export function DeviconCoffeescript(p: PartialProps): React.JSX.Element
export function DeviconComposer(p: PartialProps): React.JSX.Element
export function DeviconConfluence(p: PartialProps): React.JSX.Element
export function DeviconCouchdb(p: PartialProps): React.JSX.Element
export function DeviconCplusplus(p: PartialProps): React.JSX.Element
export function DeviconCsharp(p: PartialProps): React.JSX.Element
export function DeviconCss3(p: PartialProps): React.JSX.Element
export function DeviconCucumber(p: PartialProps): React.JSX.Element
export function DeviconD3js(p: PartialProps): React.JSX.Element
export function DeviconDebian(p: PartialProps): React.JSX.Element
export function DeviconDevicon(p: PartialProps): React.JSX.Element
export function DeviconDjango(p: PartialProps): React.JSX.Element
export function DeviconDocker(p: PartialProps): React.JSX.Element
export function DeviconDoctrine(p: PartialProps): React.JSX.Element
export function DeviconDotnet(p: PartialProps): React.JSX.Element
export function DeviconDrupal(p: PartialProps): React.JSX.Element
export function DeviconElectron(p: PartialProps): React.JSX.Element
export function DeviconEleventy(p: PartialProps): React.JSX.Element
export function DeviconElm(p: PartialProps): React.JSX.Element
export function DeviconEmber(p: PartialProps): React.JSX.Element
export function DeviconErlang(p: PartialProps): React.JSX.Element
export function DeviconExpress(p: PartialProps): React.JSX.Element
export function DeviconFacebook(p: PartialProps): React.JSX.Element
export function DeviconFirebase(p: PartialProps): React.JSX.Element
export function DeviconFirefox(p: PartialProps): React.JSX.Element
export function DeviconFlask(p: PartialProps): React.JSX.Element
export function DeviconFlutter(p: PartialProps): React.JSX.Element
export function DeviconFoundation(p: PartialProps): React.JSX.Element
export function DeviconGatling(p: PartialProps): React.JSX.Element
export function DeviconGatsby(p: PartialProps): React.JSX.Element
export function DeviconGimp(p: PartialProps): React.JSX.Element
export function DeviconGit(p: PartialProps): React.JSX.Element
export function DeviconGithub(p: PartialProps): React.JSX.Element
export function DeviconGitlab(p: PartialProps): React.JSX.Element
export function DeviconGo(p: PartialProps): React.JSX.Element
export function DeviconGoogle(p: PartialProps): React.JSX.Element
export function DeviconGooglecloud(p: PartialProps): React.JSX.Element
export function DeviconGradle(p: PartialProps): React.JSX.Element
export function DeviconGrails(p: PartialProps): React.JSX.Element
export function DeviconGroovy(p: PartialProps): React.JSX.Element
export function DeviconGrunt(p: PartialProps): React.JSX.Element
export function DeviconGulp(p: PartialProps): React.JSX.Element
export function DeviconHandlebars(p: PartialProps): React.JSX.Element
export function DeviconHaskell(p: PartialProps): React.JSX.Element
export function DeviconHaxe(p: PartialProps): React.JSX.Element
export function DeviconHeroku(p: PartialProps): React.JSX.Element
export function DeviconHtml5(p: PartialProps): React.JSX.Element
export function DeviconIe10(p: PartialProps): React.JSX.Element
export function DeviconIllustrator(p: PartialProps): React.JSX.Element
export function DeviconInkscape(p: PartialProps): React.JSX.Element
export function DeviconIntellij(p: PartialProps): React.JSX.Element
export function DeviconIonic(p: PartialProps): React.JSX.Element
export function DeviconJasmine(p: PartialProps): React.JSX.Element
export function DeviconJava(p: PartialProps): React.JSX.Element
export function DeviconJavascript(p: PartialProps): React.JSX.Element
export function DeviconJeet(p: PartialProps): React.JSX.Element
export function DeviconJenkins(p: PartialProps): React.JSX.Element
export function DeviconJetbrains(p: PartialProps): React.JSX.Element
export function DeviconJquery(p: PartialProps): React.JSX.Element
export function DeviconKotlin(p: PartialProps): React.JSX.Element
export function DeviconKrakenjs(p: PartialProps): React.JSX.Element
export function DeviconKubernetes(p: PartialProps): React.JSX.Element
export function DeviconLaravel(p: PartialProps): React.JSX.Element
export function DeviconLess(p: PartialProps): React.JSX.Element
export function DeviconLinkedin(p: PartialProps): React.JSX.Element
export function DeviconLinux(p: PartialProps): React.JSX.Element
export function DeviconMaterialui(p: PartialProps): React.JSX.Element
export function DeviconMeteor(p: PartialProps): React.JSX.Element
export function DeviconMicrosoftsqlserver(p: PartialProps): React.JSX.Element
export function DeviconMocha(p: PartialProps): React.JSX.Element
export function DeviconMongodb(p: PartialProps): React.JSX.Element
export function DeviconMoodle(p: PartialProps): React.JSX.Element
export function DeviconMysql(p: PartialProps): React.JSX.Element
export function DeviconNestjs(p: PartialProps): React.JSX.Element
export function DeviconNginx(p: PartialProps): React.JSX.Element
export function DeviconNodejs(p: PartialProps): React.JSX.Element
export function DeviconNodewebkit(p: PartialProps): React.JSX.Element
export function DeviconNpm(p: PartialProps): React.JSX.Element
export function DeviconObjectivec(p: PartialProps): React.JSX.Element
export function DeviconOracle(p: PartialProps): React.JSX.Element
export function DeviconPhotoshop(p: PartialProps): React.JSX.Element
export function DeviconPhp(p: PartialProps): React.JSX.Element
export function DeviconPhpstorm(p: PartialProps): React.JSX.Element
export function DeviconPostgresql(p: PartialProps): React.JSX.Element
export function DeviconPremierepro(p: PartialProps): React.JSX.Element
export function DeviconProtractor(p: PartialProps): React.JSX.Element
export function DeviconPycharm(p: PartialProps): React.JSX.Element
export function DeviconPython(p: PartialProps): React.JSX.Element
export function DeviconRails(p: PartialProps): React.JSX.Element
export function DeviconReact(p: PartialProps): React.JSX.Element
export function DeviconRedhat(p: PartialProps): React.JSX.Element
export function DeviconRedis(p: PartialProps): React.JSX.Element
export function DeviconRedux(p: PartialProps): React.JSX.Element
export function DeviconRocksdb(p: PartialProps): React.JSX.Element
export function DeviconRuby(p: PartialProps): React.JSX.Element
export function DeviconRubymine(p: PartialProps): React.JSX.Element
export function DeviconRust(p: PartialProps): React.JSX.Element
export function DeviconSafari(p: PartialProps): React.JSX.Element
export function DeviconSass(p: PartialProps): React.JSX.Element
export function DeviconScala(p: PartialProps): React.JSX.Element
export function DeviconSequelize(p: PartialProps): React.JSX.Element
export function DeviconSketch(p: PartialProps): React.JSX.Element
export function DeviconSlack(p: PartialProps): React.JSX.Element
export function DeviconSourcetree(p: PartialProps): React.JSX.Element
export function DeviconSqlalchemy(p: PartialProps): React.JSX.Element
export function DeviconSsh(p: PartialProps): React.JSX.Element
export function DeviconStylus(p: PartialProps): React.JSX.Element
export function DeviconSwift(p: PartialProps): React.JSX.Element
export function DeviconSymfony(p: PartialProps): React.JSX.Element
export function DeviconTomcat(p: PartialProps): React.JSX.Element
export function DeviconTravis(p: PartialProps): React.JSX.Element
export function DeviconTrello(p: PartialProps): React.JSX.Element
export function DeviconTwitter(p: PartialProps): React.JSX.Element
export function DeviconTypescript(p: PartialProps): React.JSX.Element
export function DeviconTypo3(p: PartialProps): React.JSX.Element
export function DeviconUbuntu(p: PartialProps): React.JSX.Element
export function DeviconUwsgi(p: PartialProps): React.JSX.Element
export function DeviconVagrant(p: PartialProps): React.JSX.Element
export function DeviconVim(p: PartialProps): React.JSX.Element
export function DeviconVisualstudio(p: PartialProps): React.JSX.Element
export function DeviconVuejs(p: PartialProps): React.JSX.Element
export function DeviconWebpack(p: PartialProps): React.JSX.Element
export function DeviconWebstorm(p: PartialProps): React.JSX.Element
export function DeviconWindows8(p: PartialProps): React.JSX.Element
export function DeviconWoocommerce(p: PartialProps): React.JSX.Element
export function DeviconWordpress(p: PartialProps): React.JSX.Element
export function DeviconXd(p: PartialProps): React.JSX.Element
export function DeviconYarn(p: PartialProps): React.JSX.Element
export function DeviconYii(p: PartialProps): React.JSX.Element
export function DeviconYunohost(p: PartialProps): React.JSX.Element
export function DeviconZend(p: PartialProps): React.JSX.Element
