name: Get releases
on:
  - push
  - workflow_dispatch
jobs:
  get:
    name: Get all releases from Devicon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: .github/scripts/get-releases.js

