name: React library
on: [workflow_dispatch]
jobs:
  generate:
    name: Generate React library
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - env:
          SPATH: ./.github/scripts/react-lib.js
        run: |
          chmod +x ${{ env.SPATH }}
          node ${{ env.SPATH }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: | 
            ✅ "@devapix/react" library generated successfully! 
            ⚠️ Don't forget to publish on npm!
